-- 2. Ministries
CREATE TABLE IF NOT EXISTS ministries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(10),
    name_ar TEXT NOT NULL,
    name_en TEXT,
    name_fr TEXT NOT NULL,
    address TEXT,
    email TEXT,
    phone TEXT,
    phone2 TEXT,
    fax TEXT,
    fax2 TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    parent_id UUID REFERENCES ministries(id),
    description TEXT
);

-- Insert ministries data
INSERT INTO ministries (
    id, name_fr, code, description, parent_id, address, email, phone, 
    is_active, name_ar, name_en, phone2, fax, fax2
) VALUES 
('041cfce7-eedb-408e-90de-ac92f6611696', 
    'Ministère du Commerce Intérieur et de la Régulation du Marché National', 
    'MCI', 
    'Organisation des marchés nationaux.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التجارة الداخلية وتنظيم السوق الوطني', 
    'Ministry of Internal Trade and Regulation of the National Market', 
    null, 
    '+213', 
    null
),
('07d625e3-ac56-4bd0-9f2c-9ad0c053e934', 
    'Ministère de l''Énergie, des Mines et des Énergies Renouvelables', 
    'MENR', 
    'Supervise les ressources énergétiques et minières.', 
    null, 
    'Hydra, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الطاقة والمناجم والطاقات المتجددة', 
    'Ministry of Energy, Mines, and Renewable Energies', 
    null, 
    '+213', 
    null
),
('0c2db0f3-d1eb-4e03-aa36-7a3f4e70f9f0', 
    'Ministère du Tourisme et de l''Artisanat', 
    'MTU', 
    'Promotion touristique et artisanale.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة السياحة والصناعة التقليدية', 
    'Ministry of Tourism and Handicrafts', 
    null, 
    '+213', 
    null
),
('0c476b47-ac8b-4262-9eb4-9f121cc1ecf1', 
    'Ministère des Finances', 
    'MF', 
    'Gestion du budget de l''État et des politiques financières.', 
    null, 
    'Alger Centre', 
    null, 
    '+213', 
    'true', 
    'وزارة المالية', 
    'Ministry of Finance', 
    null, 
    '+213', 
    null
),
('0feb88bc-dbf0-4080-aae3-b6584b634f8b', 
    'Ministère de l''Industrie et de la Production Pharmaceutique', 
    'MIPP', 
    'Développement industriel et pharmaceutique.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الصناعة والإنتاج الصيدلاني', 
    'Ministry of Industry and Pharmaceutical Production', 
    null, 
    '+213', 
    null
),
('146f34b9-fa49-49f6-89a5-d2abc5cc8a25', 
    'Haut Conseil Islamique', 
    'HCI', 
    'Promotion des valeurs islamiques.', 
    null, 
    'Bir Mourad Raïs, Alger', 
    'contact@hci.dz', 
    '+213 21 67 89 45', 
    'true', 
    'المجلس الإسلامي الأعلى', 
    'High Islamic Council', 
    null, 
    '+213 21 67 89 46', 
    null
),
('17f662d1-754f-43d8-a8c8-d2b0e97c4356', 
    'Ministère des Travaux Publics et des Infrastructures de Base', 
    'MTP', 
    'Construction et entretien des infrastructures.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الأشغال العمومية والبنى التحتية الأساسية', 
    'Ministry of Public Works and Basic Infrastructure', 
    null, 
    '+213', 
    null
),
('19d34e7f-35e0-4e65-a3bb-ba03d24ae483', 
    'Conseil de la Nation', 
    'CN', 
    'Chambre haute du Parlement algérien.', 
    null, 
    'Palais du Conseil, El Mouradia, Alger', 
    'contact@conseil-nation.dz', 
    '+213 21 60 45 67', 
    'true', 
    'مجلس الأمة', 
    'Council of the Nation', 
    null, 
    '+213 21 60 89 10', 
    null
),
('1bfc9b4b-f5e5-41c3-9350-161ad4862208', 
    'Conseil National Économique, Social et Environnemental', 
    'CNESE', 
    'Dialogue, concertation sur les politiques publiques.', 
    null, 
    'El Madania, Alger', 
    'info@cnese.dz', 
    '+213 21 64 32 10', 
    'true', 
    'المجلس الوطني الاقتصادي والاجتماعي والبيئي', 
    'National Economic, Social and Environmental Council', 
    null, 
    '+213 21 64 32 11', 
    null
),
('1ca0a183-bb96-43ee-9e89-7fc9e3e4330a', 
    'Ministère de la Solidarité Nationale, de la Famille et de la Condition de la Femme', 
    'MSN', 
    'Soutien aux familles et aux personnes vulnérables.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التضامن الوطني والأسرة وقضايا المرأة', 
    'Ministry of National Solidarity, Family and Women''s Affairs', 
    null, 
    '+213', 
    null
),
('1e86897d-a003-4935-942c-e70c153848ec', 
    'Ministère des Transports', 
    'MT', 
    'Développement et régulation du transport.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة النقل', 
    'Ministry of Transport', 
    null, 
    '+213', 
    null
),
('31e460cd-7c84-483f-8561-5dce104d6b6e', 
    'Ministère de la Communication', 
    'MC', 
    'Régulation et développement des médias.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الاتصال', 
    'Ministry of Communication', 
    null, 
    '+213', 
    null
),
('32718f95-540f-472c-af72-e1ad29ccb982', 
    'Ministère de l''Intérieur, des Collectivités Locales et de l''Aménagement du Territoire', 
    'MI', 
    'Garant de la sécurité intérieure et du développement local.', 
    null, 
    'Place Mohamed Belouizdad, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الداخلية والجماعات المحلية والتهيئة العمرانية', 
    'Ministry of the Interior, Local Authorities, and Regional Planning', 
    null, 
    '+213', 
    null
),
('3292ee1c-8b28-46a1-a303-18529ff1053a', 
    'Haute Autorité de Transparence, de Prévention et de Lutte contre la Corruption', 
    'HATPLC', 
    'Prévention et lutte contre la corruption.', 
    null, 
    'Bir Mourad Raïs, Alger', 
    'contact@hatplc.dz', 
    '+213 21 77 88 99', 
    'true', 
    'الهيئة العليا للشفافية والوقاية من الفساد ومكافحته', 
    'High Authority for Transparency, Prevention and Fight Against Corruption', 
    null, 
    '+213 21 77 88 66', 
    null
),
('35bebe4f-4fcb-47c4-901e-4b3bc7b96ee4', 
    'Conseil Supérieur de la Langue Arabe', 
    'CSLA', 
    'Promotion de la langue arabe en Algérie.', 
    null, 
    'Val d''Hydra, Alger', 
    'info@csla.dz', 
    '+213 21 70 80 90', 
    'true', 
    'المجلس الأعلى للغة العربية', 
    'High Council of the Arabic Language', 
    null, 
    '+213 21 70 80 91', 
    null
),
('39080ab4-53e6-4f91-9b2c-c4ba5f416e72', 
    'Assemblée Populaire Nationale', 
    'APN', 
    'Législation et contrôle de l''action gouvernementale.', 
    null, 
    'Rue des Fusillés, El Mouradia, Alger', 
    'contact@apn.dz', 
    '+213 21 60 12 34', 
    'true', 
    'المجلس الشعبي الوطني', 
    'National People''s Assembly', 
    null, 
    '+213 21 60 56 78', 
    null
),
('480b491b-052f-4d8a-96a6-b06e23b2bb14', 
    'Ministère des Affaires Étrangères, de la Communauté Nationale à l''Étranger et des Affaires Africaines', 
    'MAE', 
    'Gère la diplomatie et la diaspora nationale.', 
    null, 
    'Plateau des Anassers, Kouba, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الشؤون الخارجية والجالية الوطنية بالخارج والشؤون الإفريقية', 
    'Ministry of Foreign Affairs, National Community Abroad and African Affairs', 
    null, 
    '+213', 
    null
),
('4aa8af5d-4173-438f-8bee-ca3954dbf55c', 
    'Ministère du Commerce Extérieur et de la Promotion des Exportations', 
    'MCE', 
    'Développement du commerce international.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التجارة الخارجية وترقية الصادرات', 
    'Ministry of Foreign Trade and Export Promotion', 
    null, 
    '+213', 
    null
),
('4b80853b-1a44-49b9-9cdb-f7077db555d7', 
    'Cour Suprême', 
    'CS', 
    'Contrôle et unification de la jurisprudence.', 
    null, 
    'El Madania, Alger', 
    'contact@cour-supreme.dz', 
    '+213 21 65 78 90', 
    'true', 
    'المحكمة العليا', 
    'Supreme Court', 
    null, 
    '+213 21 65 43 21', 
    null
),
('5212c2ce-08b0-4fd5-9443-58df8a26daf2', 
    'Ministère des Sports', 
    'MSP', 
    'Promotion du sport et de la performance nationale.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الرياضة', 
    'Ministry of Sports', 
    null, 
    '+213', 
    null
),
('633a15a0-787d-4a8c-b32e-9117dbe700df', 
    'Observatoire National de la Société Civile', 
    'ONSC', 
    'Promotion et encadrement de la société civile.', 
    null, 
    'Bir Mourad Raïs, Alger', 
    'info@onsc.dz', 
    '+213 21 87 88 89', 
    'true', 
    'المرصد الوطني للمجتمع المدني', 
    'National Observatory of Civil Society', 
    null, 
    '+213 21 87 88 90', 
    null
),
('65aad606-cd27-4290-9154-07fb8477e1b6', 
    'Ministère de la Justice, Garde des Sceaux', 
    'MJ', 
    'Organisation judiciaire et sauvegarde de l''État de droit.', 
    null, 
    'El Biar, Alger', 
    'contact@mjustice.dz', 
    '+213 23 38 35 37', 
    'true', 
    'وزارة العدل، حافظ الأختام', 
    'Ministry of Justice, Keeper of the Seals', 
    null, 
    '+213 23 38 35 50', 
    null
),
('66f58abe-6c51-4eb6-81bc-58f44ddaa4b2', 
    'Présidence de la République', 
    'PR', 
    'Assure la plus haute fonction exécutive et représente l''État.', 
    null, 
    'El Mouradia, Alger', 
    null, 
    '+213', 
    'true', 
    'رئاسة الجمهورية', 
    'Presidency of the Republic', 
    null, 
    '+213', 
    null
),
('67cc3e55-e422-4c06-9e8c-0c0e9ad0ef58', 
    'Ministère de l''Économie de la Connaissance, des Start-ups et des Micro-entreprises', 
    'MEK', 
    'Développement des start-ups et de l''économie numérique.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة اقتصاد المعرفة والمؤسسات الناشئة والمؤسسات المصغرة', 
    'Ministry of Knowledge Economy, Start-ups and Micro-enterprises', 
    null, 
    '+213', 
    null
),
('715090b3-85fd-4fea-9255-047ee2af8978', 
    'Conseil Supérieur de la Jeunesse', 
    'CSJ', 
    'Encadrement et soutien à la jeunesse algérienne.', 
    null, 
    'El Madania, Alger', 
    'contact@csj.dz', 
    '+213 21 89 90 91', 
    'true', 
    'المجلس الأعلى للشباب', 
    'High Council for Youth', 
    null, 
    '+213 21 89 90 92', 
    null
),
('78a39bbc-c2d0-4d59-b05a-4499dd21171f', 
    'Autorité Nationale Indépendante des Élections', 
    'ANIE', 
    'Organisation, supervision des élections.', 
    null, 
    'Val d''Hydra, Alger', 
    'contact@anie.dz', 
    '+213 21 99 88 77', 
    'true', 
    'السلطة الوطنية المستقلة للانتخابات', 
    'National Independent Authority for Elections', 
    null, 
    '+213 21 99 88 66', 
    null
),
('7eebd9fd-816a-4135-9fe8-b413e3cc997a', 
    'Services du Premier ministre', 
    'SPM', 
    'Coordination de l''action gouvernementale.', 
    null, 
    'Palais du Gouvernement, Alger', 
    null, 
    '+213', 
    'true', 
    'مصالح الوزير الأول', 
    'Services of the Prime Minister', 
    null, 
    '+213', 
    null
),
('7fec8310-3abf-49c6-90ac-f303a0859c2a', 
    'Conseil Supérieur de la Magistrature', 
    'CSM', 
    'Garant de l''indépendance du pouvoir judiciaire.', 
    null, 
    'El Madania, Alger', 
    'csm@justice.dz', 
    '+213 21 66 77 88', 
    'true', 
    'المجلس الأعلى للقضاء', 
    'High Council of the Judiciary', 
    null, 
    '+213 21 66 55 44', 
    null
),
('80c3e210-fa54-4e4f-bb39-1a251905e1a8', 
    'Conseil d''État', 
    'CE', 
    'Instance suprême du contentieux administratif.', 
    null, 
    'El Madania, Alger', 
    'info@conseil-etat.dz', 
    '+213 21 45 67 89', 
    'true', 
    'مجلس الدولة', 
    'Council of State', 
    null, 
    '+213 21 45 12 34', 
    null
),
('80da0ce9-4412-4e3e-9f75-2b6560428f8f', 
    'Ministère de la Santé', 
    'MS', 
    'Protection sanitaire et promotion de la santé publique.', 
    null, 
    'Belouizdad, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الصحة', 
    'Ministry of Health', 
    null, 
    '+213', 
    null
),
('84ad7cde-b5af-44dd-b3c3-59c3856bcca2', 
    'Ministère du Travail, de l''Emploi et de la Sécurité Sociale', 
    'MTESS', 
    'Gestion de l''emploi et de la protection sociale.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة العمل والتشغيل والضمان الاجتماعي', 
    'Ministry of Labour, Employment and Social Security', 
    null, 
    '+213', 
    null
),
('89ba5f7d-dcd5-4863-9735-d67b1a1d3fec', 
    'Ministère de l''Hydraulique', 
    'MHY', 
    'Gestion des ressources hydriques.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الموارد المائية', 
    'Ministry of Water Resources', 
    null, 
    '+213', 
    null
),
('9d7abf27-35f2-4445-ac27-b68b4b0c9bfd', 
    'Ministère des Affaires Religieuses et des Wakfs', 
    'MRA', 
    'Encadrement du culte religieux.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الشؤون الدينية والأوقاف', 
    'Ministry of Religious Affairs and Endowments', 
    null, 
    '+213', 
    null
),
('9df14c2c-15ac-4f6b-9334-6e8a1858bd1b', 
    'Conseil National des Droits de l''Homme', 
    'CNDH', 
    'Protection et promotion des droits de l''Homme.', 
    null, 
    'Hydra, Alger', 
    'contact@cndh.dz', 
    '+213 21 75 84 93', 
    'true', 
    'المجلس الوطني لحقوق الإنسان', 
    'National Human Rights Council', 
    null, 
    '+213 21 75 84 94', 
    null
),
('ab50a7ba-2ccf-4756-b046-81d6beadda75', 
    'Ministère de la Culture et des Arts', 
    'MCA', 
    'Promotion culturelle et artistique.', 
    null, 
    'Alger Centre', 
    null, 
    '+213', 
    'true', 
    'وزارة الثقافة والفنون', 
    'Ministry of Culture and Arts', 
    null, 
    '+213', 
    null
),
('ada2c974-4cd7-40c2-a5e6-20a8ef55ebca', 
    'Ministère de l''Habitat, de l''Urbanisme et de la Ville', 
    'MHU', 
    'Aménagement urbain et construction de logements.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة السكن والعمران والمدينة', 
    'Ministry of Housing, Urban Planning, and the City', 
    null, 
    '+213', 
    null
),
('afa92087-b61e-4748-a9fc-ef4add0580e2', 
    'Ministère de la Défense Nationale', 
    'MDN', 
    'Assure la défense et la sécurité nationale.', 
    null, 
    'Tagarins, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الدفاع الوطني', 
    'Ministry of National Defense', 
    null, 
    '+213', 
    null
),
('b624c68f-9a7a-43cf-9fb7-85ab4d468b27', 
    'Ministère de l''Éducation Nationale', 
    'MEN', 
    'Supervise le système éducatif national.', 
    null, 
    'El Mouradia, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التربية الوطنية', 
    'Ministry of National Education', 
    null, 
    '+213', 
    null
),
('bd8fe809-c3ee-45d2-ad66-937f6e77f292', 
    'Académie Algérienne des Sciences et Technologies', 
    'AAST', 
    'Développement scientifique et technologique.', 
    null, 
    'El Harrach, Alger', 
    'info@aast.dz', 
    '+213 21 85 96 07', 
    'true', 
    'الأكاديمية الجزائرية للعلوم والتكنولوجيا', 
    'Algerian Academy of Sciences and Technologies', 
    null, 
    '+213 21 85 96 08', 
    null
),
('c10f25ce-d5f3-4fbf-a3ad-eaf5e660207f', 
    'Cour des Comptes', 
    'CDC', 
    'Contrôle du patrimoine public et des finances de l''État.', 
    null, 
    'Rue Colonel Amirouche, Alger', 
    'contact@courdescomptes.dz', 
    '+213 21 73 85 60', 
    'true', 
    'مجلس المحاسبة', 
    'Court of Auditors', 
    null, 
    '+213 21 73 85 70', 
    null
),
('c4694af4-b6dd-4512-bd47-750410f4c44d', 
    'Ministère de l''Environnement et de la Qualité de Vie', 
    'MEQ', 
    'Préservation de l''environnement et développement durable.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة البيئة وجودة الحياة', 
    'Ministry of Environment and Quality of Life', 
    null, 
    '+213', 
    null
),
('c5ee78eb-d947-4ddc-922b-a615dd07c334', 
    'Conseil National de la Recherche Scientifique et des Technologies', 
    'CNRST', 
    'Promotion de la recherche scientifique.', 
    null, 
    'Baba Hassen, Alger', 
    'contact@cnrst.dz', 
    '+213 21 86 97 09', 
    'true', 
    'المجلس الوطني للبحث العلمي والتكنولوجيات', 
    'National Council for Scientific Research and Technologies', 
    null, 
    '+213 21 86 97 10', 
    null
),
('c95ceaf9-fb59-4009-89e2-b69ac53bf99f', 
    'Ministère des Moudjahidine et des Ayants Droit', 
    'MPLF', 
    'Préservation de la mémoire nationale.', 
    null, 
    'El Madania, Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة المجاهدين وذوي الحقوق', 
    'Ministry of Mujahideen and Rights Holders', 
    null, 
    '+213', 
    null
),
('cdeb8109-5fd7-47b2-82a7-a4c10148ec0e', 
    'Ministère de la Formation et de l''Enseignement Professionnels', 
    'MFEP', 
    'Développement de la formation professionnelle.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التكوين والتعليم المهنيين', 
    'Ministry of Vocational Training and Education', 
    null, 
    '+213', 
    null
),
('cf086abd-d853-4f01-8592-79ea48e1f127', 
    'Ministère de la Jeunesse', 
    'MJ', 
    'Développement des politiques de jeunesse.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة الشباب', 
    'Ministry of Youth', 
    null, 
    '+213', 
    null
),
('d226e11b-3b82-4f3c-9769-5d448ebf00ae', 
    'Ministère de l''Enseignement Supérieur et de la Recherche Scientifique', 
    'MESRS', 
    'Développement de la recherche et des universités.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة التعليم العالي والبحث العلمي', 
    'Ministry of Higher Education and Scientific Research', 
    null, 
    '+213', 
    null
),
('e356bde9-28bf-4e6e-a4d2-9065a8439296', 
    'Ministère de l''Agriculture, du Développement Rural et de la Pêche', 
    'MAGRI', 
    'Développement rural et agriculture durable.', 
    null, 
    'Hydra, Alger', 
    '', 
    '+213', 
    'true', 
    'وزارة الفلاحة والتنمية الريفية والصيد البحري', 
    'Ministry of Agriculture, Rural Development, and Fisheries', 
    null, 
    '+213', 
    null
),
('f06f899b-b5ce-4090-98ab-639b8442d052', 
    'Cour Constitutionnelle', 
    'CC', 
    'Vérification de la conformité des lois à la Constitution.', 
    null, 
    'Rue de la Constitution, El Madania, Alger', 
    'info@courconstitutionnelle.dz', 
    '+213 21 50 12 34', 
    'true', 
    'المحكمة الدستورية', 
    'Constitutional Court', 
    null, 
    '+213 21 50 56 78', 
    null
),
('fc84b236-8154-4c83-b013-7f1da7c76fbe', 
    'Ministère de la Poste et des Télécommunications', 
    'MPT', 
    'Gestion des communications postales et électroniques.', 
    null, 
    'Alger', 
    null, 
    '+213', 
    'true', 
    'وزارة البريد والمواصلات', 
    'Ministry of Post and Telecommunications', 
    null, 
    '+213', 
    null
),
('34f8bf2b-a020-469f-9351-841b32da7fd6', 
    'Ministère des Relations avec le Parlement', 
    'MRP', 
    'Gestion des communications postales et électroniques.', 
    null, 
    '12 شارع علي بجاوي الابيار الجزائر', 
    'info@mrp.gov.dz', 
    '+213 23 05 32 84', 
    'true', 
    'وزارة العلاقات مع البرلمان', 
    'Ministry of Relations with Parliament', 
    null, 
    '+213 23 05 32 85', 
    null
);