CREATE TABLE "operations" (
    "DRB"	VARCHAR(512),
    "Province"	VARCHAR(512),
    "Program_Type"	VARCHAR(512),
    "Program_Portfolio"	VARCHAR(512),
    "Program_Title"	VARCHAR(512),
    "Subprogram_Title"	VARCHAR(512),
    "Individualization_Number"	VARCHAR(512),
    "Operation_Title"	VARCHAR(512),
    "Notification_Year"	VARCHAR(512),
    "Initial_AE"	VARCHAR(512),
    "Current_AE"	INT,
    "AE_Cumulative_Commitment"	VARCHAR(512),
    "Cumulative_Payments"	VARCHAR(512),
    "CP_2025"	VARCHAR(512),
    "Remaining_Balance_March2025"	VARCHAR(512),
    "Physical_Rate"	VARCHAR(512),
    "Observation"	VARCHAR(512),
    "Reevaluation_2025"	VARCHAR(512)
);

INSERT INTO "operations" (
    "DRB", "Province", "Program_Type", "Program_Portfolio", "Program_Title", 
    "Subprogram_Title", "Individualization_Number", "Operation_Title", "Notification_Year", 
    "Initial_AE", "Current_AE", "AE_Cumulative_Commitment", "Cumulative_Payments", 
    "CP_2025", "Remaining_Balance_March2025", "Physical_Rate", "Observation", "Reevaluation_2025"
) VALUES
	('Oran', '27-Mostaganem', 'PSD', 'Portfeuille 024. Travaux publics et des infrastructures de base', '', '', 'NK5.523.2.262.010.44
', 'réalisation de la ligne ferroviaire reliant Hassi Mefsoukh et Mostaganem
N° de l’opération', '', '', '28662460245', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Affaires Religieuses et des Wakfs', '', '', '', 'Suivi, réalisation et équipement d’une mosquée pôle à Mascara', '', '', '2504000000', '', '', '25000000', '', '', '', '300000000'),
	('Oran', '29-Mascara', 'PSD', 'Enseignement Supérieur et de la Recherche Scientifique', '', '', '', 'Suivi et réalisation de 6.000 places pédagogiques y compris une salle OMS, un terrain de football, une piscine semi-olympique et un théâtre de verdure à Mascara', '', '', '4642710000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Jeunesse et Sports', '', '', '', 'Suivi, réalisation et équipement d’un vélodrome à Mascara  ', '', '', '2577000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Industrie Et De La Production Pharmaceutique', '', '', '', 'Suivi et réalisation d’une zone industrielle 98 H à Oggaz, wilaya de Mascara (tranche 2)', '', '', '1000000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'T3', 'Agriculture et du Développement Rural', '', '', '', 'Etude d’adaptation, suivi , contrôle et travaux de réalisation et équipement de 09 centres de proximité pour le stockage intermédiaire des céréales au niveau de la wilaya de Mascarad’engagement :  DA', '', '', '2276743000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Travaux publics et des infrastructures de base', '', '', '', 'Réalisation d\'une pénétrante reliant l\'autoroute - oust a Mascara sur 43 km', '', '', '59 000 000 000 ', '', '', '', '', '', '', ''),
	('', '29-Mascara', 'PSD', 'Travaux publics et des infrastructures de base', '', '', '', 'Dédoublement de la RN4 sur 12 Km entre Sidi Daouad et Zeghloul', '', '', '1 500 000 000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Santé', '', '', '', 'Etude et réalisation d\'un établissement hospitalier spécialisé en urgences médicaux chirurgicales à Bouhanifia', '', '', '2623237000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSD', 'Santé', '', '', '', 'Suivi et réalisation d’un hôpital de 120 lits à Mascara', '', '', '3940000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Hydraulique', '', '', '', 'Réalisation d\'une station d\'épuration des eaux usées pour la ville de Mohammadia y compris collecteur de rejet', '', '', '2170000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Hydraulique', '', '', '', 'Etude , suivi et travaux de mise à niveau de deux (02) stations de lagunage aérés de la ville de Hacine et bouhnifia  y compris l’amélioration et réhabilitation de la collecte des rejets et intégration d’un système de traitement tertiaire (w. Mascara)', '', '', '1250000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSC', 'Travaux publics et des infrastructures de base', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSC', 'Hydraulique', '', '', '', 'Alimentation en Eau Potable de la commune de Mascara et du couloir Mohammadia - Sig à partir du Transfert MAO', '', '', '14500000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSC', 'Hydraulique', '', '', '', 'Confortement du Barrage Chorfa', '', '', '5830000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', 'PSC', 'Hydraulique', '', '', '', 'Transfert à partir du Barrage de Bouhanifia vers la retenue du Barrage de Fergoug', '', '', '10000000000', '', '', '', '', '', '', ''),
	('Oran', '20-Saida', '', 'Travaux publics et des infrastructures de base', 'infrastructure de base ', '(routes et pénétrantes) :', '', 'Réalisation Du Redoublement De La Rn06 (Carrefour Ain El Hadjar A Temetlas)', '', '', '1200000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Education et santé', '', '', '', 'Etude, Réalisation Et Equipement De 2000 Places Pédagogiques ', '', '', '1511104000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Education et santé', '', '', '', 'Etude, Realisation Et Equipement D\'Une Residence Universitaire De 1000 Lits A Saida ', '', '', '1 642 759 000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Education et santé', '', '', '', 'Suivi Et Réalisation De 2000 Places Pédagogiques ', '', '', '2037000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Education et santé', '', '', '', 'Viabilisation Et Aménagement Du Nouveau Pôle Universitaire (2 Eme Tranche', '', '', '1190611000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Développement rural et industrie', '', '', '', 'Réalisation D\'une Zone industriel/e A Sidi Ahmed (Sur 100 Ha) Wilaya De Saida (Tranche 1) »', '', '', '700000000', '', '', '', '', '', '', ''),
	('Oran', '29-Mascara', '', 'Développement rural et industrie', '', '', '', 'Réalisation D\'une Zone lndustrielle A Sidi Ahmed (Sur 100 Ha) Wilaya De Saida (Tranche 2', '', '', '1000000000', '', '', '', '', '', '', ''),
	('Oran', '31-Oran', '', 'Enseignement supérieur et de la recherche scientifique ', '', '', '', 'Étude et réalisation de 8000 lits d\'hébergement type standard et de 4280 lits améliorés (Villages méditerranéen)', '', '', '19966463', '18827752.6', '18700276', '', '', '', '', ''),
	('Oran', '31-Oran', '', 'Jeunesse et des sports ', '', '', '', 'Réalisation et équipement de la 2éme tranche stade OMS (40000) places à Oran', '', '', '11980255', '11 980 255', '11980255', '', '', '', '', ''),
	('Oran', '31-Oran', '', 'Travaux publics et infrastructures de base ', '', '', '', 'Réalisation de la deuxième rocade d\'Oran sur 21 KMs', '', '', '12839500', '12817395.17', '12759454', '', '', '', '', ''),
	('Oran', '31-Oran', '', 'Travaux publics et infrastructures de base ', '', '', '', 'Extension du terminal à conteneurs du port d\'Oran', '', '', '12370909', '12230047.15', '12219052', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'Justice', '', '', '', 'Étude, réalisation et équipement d’un établissement pénitentiaire pour 300 détenus à Ras El Ma', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'jeunesse et des sports ', '', '', '', 'Étude, réalisation et équipement d\'un centre régional des équipes nationales à Sidi Bel Abbes».', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'industrie ', '', '', '', 'd’une zone industrielle à Ras El Ma.', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'agriculture', '', '', '', 'Étude, réalisation et équipement d\'un centre de formation et de vulgarisation agricole à Sidi Bel Abbes', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'travaux publics ', '', '', '', 'Aménagement du carrefour prolongement boulevard Guermouche Med - rocade Sud avec réalisation d\'un ouvrage d\'art sous voie ferré', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'santé', '', '', '', 'l’équipement d’un centre anti cancer à Sidi Bel Abbes', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Protection du barrage de SARNO contre le déversement des eaux usées de la localité Dlahim', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Réalisation de 9.000 ML de forages y compris abris, électrification, équipement et raccordement aux réseaux existants à travers la wilaya', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Réalisation de transfert Sidi Bel Abbes vers les localités Nord de la wilaya', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Transfert des eaux de CHOTT CHERGUI vers les communes des Daïras de Telagh et Merine', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Réhabilitation de 03 stations de pompage du système de transfert des eaux du barrage de Sidi Abdelli vers Sidi Bel Abbes', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '22-Sidi Bel Abbes', '', 'l’hydraulique', '', '', '', 'Réalisation de deux réservoirs d\'une capacité de 20.000 M³ chacun au niveau du groupement urbain de Sidi Bel Abbes et leur raccordement au réseau existant', '', '', '', '', '', '', '', '', '', ''),
	('Oran', '13-Tlemcen', '', 'Travaux publics ', '', '', '', 'Réalisation du dédoublement de la route nationale 7 sur 60km entre Maghnia et Marsat Ben M’hidi', '', '', '', '', '', '', '', '', '', '');