CREATE TABLE "portfolios" (
    "Code"	INT,
    "Portefeuille de Programme"	VARCHAR(512)
);

INSERT INTO "portfolios" ("Code", "Portefeuille de Programme") VALUES
	('001', 'Présidence de la République'),
	('002', 'Services du Premier Ministre'),
	('003', 'Défense Nationale'),
	('004', 'Affaires Etrangères, Communauté Nationale à l\'Etranger et Affaires Africaines'),
	('005', 'Intérieur, Collectivités Locales et Aménagement du Territoire'),
	('006', 'Justice'),
	('007', 'Finances'),
	('008', 'Energie, Mines et Energies Renouvelables'),
	('009', 'Moudjahidine et Ayants Droits'),
	('010', 'Affaires Religieuses et Wakfs'),
	('011', 'Education Nationale'),
	('012', 'Enseignement Supérieur et  Recherche Scientifique'),
	('013', 'Formation et Enseignement Professionnels'),
	('014', 'Culture et Arts'),
	('015', 'Sports'),
	('017', 'Poste et Télécommunications'),
	('018', 'Solidarité Nationale, Famille et Condition de la Femme'),
	('019', 'Industrie et Production Pharmaceutique'),
	('020', 'Agriculture, Développement Rural et Pêche'),
	('021', 'Habitat, Urbanisme et Ville'),
	('022', 'Commerce Intérieur et Régulation du Marché National'),
	('023', 'Communication'),
	('024', 'Travaux Publics et Infrastructures de Base'),
	('025', 'Transports'),
	('026', 'Tourisme et Artisanat'),
	('027', 'Santé'),
	('028', 'Travail, Emploi et Sécurité Sociale'),
	('029', 'Relations avec le Parlement'),
	('030', 'Environnement et Qualité de la Vie'),
	('033', 'Economie de la Connaissance, Start-up et Micro-Entreprises'),
	('051', 'Hydraulique'),
	('052', 'Jeunesse'),
	('053', 'Commerce Extérieur et Promotion des Exportations'),
	('', 'S/Total Portefeuilles de Programmes \'Ministères\''),
	('500', 'Assemblée  Populaire  Nationale'),
	('501', 'Conseil de la Nation'),
	('505', 'Cour Constitutionnelle'),
	('', 'S/Total Portefeuilles de Dotations'),
	('502', 'Cour Suprême'),
	('503', 'Conseil d\'Etat'),
	('504', 'Conseil Supérieur de la Magistrature'),
	('506', 'Cour des Comptes'),
	('507', 'Haute Autorité de Transparence, de Prévention et de Lutte Contre la Corruption'),
	('508', 'Autorité Nationale Indépendante des Elections'),
	('509', 'Conseil National Economique, Social et Environnemental'),
	('510', 'Haut Conseil Islamique'),
	('511', 'Haut Conseil de la Langue Arabe'),
	('512', 'Conseil National des Droits de l\'Homme'),
	('513', 'Académie Algérienne des Sciences et des Technologies'),
	('514', 'Conseil National de la Recherche Scientifique et des Technologies'),
	('515', 'Observatoire National de la Société Civile'),
	('516', 'Conseil Superieur de la Jeunesse');