CREATE TABLE "programs" (
    "code"	INT,
    "name"	VARCHAR(512)
);

INSERT INTO "programs" ("code", "name") VALUES
	('001', 'Activité de la Présidence de la République'),
	('002', 'Coordination de l\'Activité Juridique et Gouvernementale'),
	('003', 'Médiation de la République'),
	('004', 'Promotion de la langue amazighe'),
	('005', 'Administration Générale'),
	('006', 'Activité du Premier Ministre'),
	('008', 'Fonction publique et réforme administrative'),
	('009', 'Défense Nationale'),
	('010', 'Logistique et soutien multiforme'),
	('011', 'Administration Générale'),
	('012', 'Activité diplomatique et consulaire'),
	('013', 'Administration générale'),
	('014', 'Libertés publiques et circulation des personnes et des biens'),
	('015', 'Soutien aux Collectivités locales'),
	('016', 'Aménagement du Territoire'),
	('017', 'Sûreté Nationale'),
	('018', 'Protection Civile'),
	('019', 'Transmissions Nationales'),
	('020', 'Administration Générale'),
	('021', 'Activité judiciaire'),
	('022', 'Administration pénitentiaire'),
	('023', 'Répression de la corruption'),
	('024', 'Administration générale'),
	('025', 'Trésor et gestion comptable'),
	('026', 'Impôts'),
	('027', 'Budget'),
	('028', 'Domaine national'),
	('029', 'Douanes'),
	('030', 'Inspection des finances'),
	('031', 'Administration générale'),
	('700', 'Crédits non assignés'),
	('032', 'Electricité, gaz et énergies nouvelles'),
	('033', 'Mines'),
	('034', 'Compensation au titre du dessalement de l\'eau de mer'),
	('035', 'Maitrise de l\'Energie et Energies Renouvelables'),
	('036', 'Administration Générale'),
	('037', 'Patrimoine historique et culturel'),
	('038', 'Pensions'),
	('039', 'Protection sociale'),
	('040', 'Administration générale'),
	('041', 'Orientation religieuses et culture islamique'),
	('042', 'Formation et enseignement coranique'),
	('043', 'Administration générale'),
	('044', 'Enseignement'),
	('046', 'Formation'),
	('047', 'Vie scolaire et transferts sociaux'),
	('048', 'Administration générale'),
	('049', 'Enseignement et formation supérieurs'),
	('050', 'Recherche scientifique et développement technologique'),
	('051', 'Vie estudiantine'),
	('052', 'Administration générale'),
	('053', 'Formation Professionnelle'),
	('054', 'Enseignement Professionnel'),
	('055', 'Administration Générale'),
	('056', 'Arts et Lettres'),
	('057', 'Patrimoine culturel'),
	('058', 'Administration générale'),
	('060', 'Sports'),
	('061', 'Administration Générale'),
	('065', 'Développement des services postaux'),
	('066', 'Développement des télécommunications'),
	('067', 'Edification de la société algérienne  de l\'information'),
	('068', 'Administration Générale'),
	('069', 'Personnes aux besoins spécifiques'),
	('070', 'Famille et condition de la femme'),
	('071', 'Développement social et Action humanitaire'),
	('072', 'Administration générale'),
	('073', 'Compétitivité et Développement Industriels'),
	('074', 'Appui à l\'investissement'),
	('121', 'Développement et Promotion de l\'Industrie Pharmaceutique en Algerie'),
	('075', 'Administration Générale'),
	('076', 'Agriculture et Développement Rural'),
	('077', 'Forêts'),
	('117', 'Pêche maritime'),
	('118', 'Aquaculture'),
	('119', 'Contrôle des actvités et de la qualité des produits de la pêche et de l\'aquaculture'),
	('078', 'Administration Générale'),
	('079', 'Logement'),
	('080', 'Urbanisme et aménagement'),
	('081', 'Villes et Villes nouvelles'),
	('082', 'Equipements publics'),
	('083', 'Administration générale'),
	('084', 'Régulation et Promotion de la Concurrence'),
	('085', 'Protection du Consommateur'),
	('087', 'Administration Générale'),
	('088', 'Médias et Communication institutionnelle'),
	('089', 'Administration Générale'),
	('090', 'Infrastructures routières et autoroutières'),
	('091', 'Infrastructures aéroportuaires'),
	('092', 'Infrastructures maritimes'),
	('142', 'Infrastructures ferroviaires et transports guidés'),
	('097', 'Administration générale'),
	('098', 'Mobilité et logistique'),
	('099', 'Marine marchande et ports'),
	('100', 'Aéronautique et météorologie'),
	('101', 'Administration générale'),
	('102', 'Tourisme'),
	('103', 'Artisanat et métiers'),
	('104', 'Administration générale'),
	('105', 'Prévention et soins'),
	('106', 'Formation dans le domaine de la santé'),
	('107', 'Administration générale'),
	('108', 'Inspection Générale du Travail'),
	('109', 'Soutien et promotion de l’emploi'),
	('110', 'Système de protection sociale'),
	('111', 'Administration générale'),
	('112', 'Renforcement des relations entre le Gouvernement et le Parlement'),
	('113', 'Administration générale'),
	('114', 'Environnement et développement durable'),
	('116', 'Administration Générale'),
	('123', 'Promotion de l\'économie de la connaissance, des startup et de l\'entrepreneuriat'),
	('124', 'Administration Générale'),
	('093', 'Mobilisation des ressources en eau et de la sécurité hydrique'),
	('094', 'Approvisionnement en eau potable et industrielle'),
	('095', 'Hydraulique agricole'),
	('096', 'Assainissement et protection du milieu naturel'),
	('143', 'Administration générale'),
	('059', 'Jeunesse'),
	('144', 'Administration Générale'),
	('086', 'Encadrement des Echanges Commerciaux et Promotion des Exportations'),
	('145', 'Administration Générale'),
	('', 'S/Total Portefeuilles de Programmes \'Ministères\''),
	('125', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('126', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('130', 'Cour Constitutionnelle'),
	('', 'S/Total Portefeuilles de Dotations'),
	('127', 'Contrôle et évaluation des décisions judiciaires et l\'unification de la jurisprudence'),
	('128', 'Conseil d\'Etat'),
	('129', 'Indépendance de la justice'),
	('131', 'Contrôle du patrimoine et des fonds publics'),
	('132', 'Prévention et lutte contre la corruption'),
	('133', 'Préparation, organisation, gestion et supervision de l\'ensemble des opérations éléctorales et référendaires'),
	('134', 'Dialogue ,  concertation et évaluation dans le domaine Economique, Social et Environnemental'),
	('135', 'Promotion des prescriptions religieuses islamiques'),
	('136', 'Promotion et généralisation de la langue arabe'),
	('137', 'Droits de l\'Homme'),
	('138', 'Promouvoir le développement national durable par les sciences et les technologies'),
	('139', 'Développement de la recherche scientifique et technologique'),
	('140', 'Promotion de la société civile.'),
	('141', 'Promotion  de la jeunesse');