CREATE TABLE structure (
    Code	INT,
    Structure par Activité	VARCHAR(512)
);

INSERT INTO Structure (Code, Structure par Activité) VALUES
	('001', 'Présidence de la République'),
	('001', 'Activité de la Présidence de la République'),
	('01', 'Supervision de l\'Activité Présidentielle'),
	('02', 'Sécurité et Protection'),
	('03', 'Archives et Mémoire Nationale'),
	('002', 'Coordination de l\'Activité Juridique et Gouvernementale'),
	('01', 'Coordination de l\'Activité Juridique et Gouvernementale'),
	('003', 'Médiation de la République'),
	('01', 'Médiation de la République'),
	('004', 'Promotion de la langue amazighe'),
	('01', 'Promotion de la langue amazighe'),
	('005', 'Administration Générale'),
	('01', 'Soutien Technique'),
	('02', 'Soutien Administratif'),
	('002', 'Services du Premier Ministre'),
	('006', 'Activité du Premier Ministre'),
	('01', 'Gestion, coordination et suivi de l’activité du gouvernement'),
	('02', 'Soutien technique'),
	('008', 'Fonction publique et réforme administrative'),
	('01', 'Fonction publique'),
	('02', 'Réforme administrative'),
	('03', 'Soutien administratif'),
	('003', 'Défense Nationale'),
	('009', 'Défense Nationale'),
	('00', 'Défense Nationale'),
	('010', 'Logistique et soutien multiforme'),
	('00', 'Logistique et soutien multiforme'),
	('011', 'Administration Générale'),
	('00', 'Administration générale'),
	('004', 'Affaires Etrangères, Communauté Nationale à l\'Etranger et Affaires Africaines'),
	('012', 'Activité diplomatique et consulaire'),
	('01', 'Diplomatie et relations extérieures'),
	('02', 'Affaires consulaires et communauté nationale à l\'étranger'),
	('013', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('005', 'Intérieur, Collectivités Locales et Aménagement du Territoire'),
	('014', 'Libertés publiques et circulation des personnes et des biens'),
	('01', 'Mouvement associatif et vie politique'),
	('02', 'Etat de circulation des personnes et des biens'),
	('03', 'Identité, titres et documents sécurisés'),
	('04', 'Numérisation du service public'),
	('015', 'Soutien aux Collectivités locales'),
	('01', 'Missions dévolues aux collectivités locales'),
	('02', 'Appui au développement socio-économique des collectivités locales'),
	('016', 'Aménagement du Territoire'),
	('01', 'Instruments de l\'aménagement du territoire'),
	('02', 'Développement  et Attractivité du Territoire'),
	('017', 'Sûreté Nationale'),
	('01', 'Soutien administratif et logistique central et régional'),
	('02', 'Sécurité, ordre public, prévention  et intervention'),
	('03', 'Activités socio-professionnelles'),
	('018', 'Protection Civile'),
	('01', 'Intervention et Prévention'),
	('02', 'Soutien administratif et logistique'),
	('019', 'Transmissions Nationales'),
	('01', 'Réseaux des transmissions'),
	('02', 'Soutien administratif et logistique'),
	('020', 'Administration Générale'),
	('01', 'Soutient Administratif et logistique'),
	('02', 'Risques majeurs'),
	('03', 'Sécurité routière'),
	('006', 'Justice'),
	('021', 'Activité judiciaire'),
	('01', 'Activité judiciaire ordinaire et administrative'),
	('02', 'Soutien administratif'),
	('03', 'Compte de la pension alimentaire '),
	('022', 'Administration pénitentiaire'),
	('01', 'Conditions de détention'),
	('02', 'Réinsertion sociale'),
	('03', 'Sécurité'),
	('04', 'Soutien administratif'),
	('023', 'Répression de la corruption'),
	('01', 'Stratégie, Appui technique et administratif'),
	('02', 'Investigations et recherches'),
	('024', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('007', 'Finances'),
	('025', 'Trésor et gestion comptable'),
	('01', 'Gestion financière de l\'Etat'),
	('02', 'Modernisation des systèmes d\'information et instruments de paiement'),
	('03', 'Gestion comptable des opérations du trésor'),
	('04', 'Gestion des moyens et soutien administratif'),
	('026', 'Impôts'),
	('01', 'Assiette, recouvrement et Contrôle fiscal'),
	('02', 'Soutien administratif'),
	('027', 'Budget'),
	('01', 'Elaboration et suivi du budget'),
	('02', 'Contrôle de la dépense'),
	('03', 'Soutien administratif'),
	('028', 'Domaine national'),
	('01', 'Gestion des Operations domaniales'),
	('02', 'Conservation et cadastre'),
	('03', 'Soutien administratif'),
	('029', 'Douanes'),
	('01', 'Recouvrement douanier'),
	('02', 'Contrôles et Protection de l’Economie  nationale'),
	('03', 'Soutien administratif'),
	('030', 'Inspection des finances'),
	('01', 'Contrôle administratif des finances publiques  et des capitaux marchands de l\'Etat'),
	('02', 'Soutien administratif'),
	('031', 'Administration générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien administratif'),
	('700', 'Crédits non assignés'),
	('00', 'Crédits non assignés'),
	('008', 'Energie, Mines et Energies Renouvelables'),
	('032', 'Electricité, gaz et énergies nouvelles'),
	('01', 'Electrification'),
	('02', 'Distribution publique du gaz'),
	('03', 'Programme spéciaux de l\'électricité et du gaz'),
	('04', 'Energies nouvelles'),
	('05', 'Soutien de l\'Etat à la facturation de l\'électricité'),
	('033', 'Mines'),
	('01', 'Mines et carrières'),
	('02', 'Ressources Minières'),
	('03', 'Développement minier'),
	('034', 'Compensation au titre du dessalement de l\'eau de mer'),
	('01', 'Compensation au titre du dessalement de l\'eau de mer'),
	('035', 'Maitrise de l\'Energie et Energies Renouvelables'),
	('01', 'Maitrise de l\'Energie'),
	('02', 'Energies Renouvelables'),
	('036', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien administratif'),
	('009', 'Moudjahidine et Ayants Droits'),
	('037', 'Patrimoine historique et culturel'),
	('01', 'Protection des symboles et des hauts -fait historique'),
	('02', 'Recherche historique et suivi des activités muséales'),
	('038', 'Pensions'),
	('01', 'Invalides et recours'),
	('02', 'Ayants droit'),
	('039', 'Protection sociale'),
	('01', 'Santé des Moudjahidine et ayants droit'),
	('02', 'Promotion sociale'),
	('040', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('010', 'Affaires Religieuses et Wakfs'),
	('041', 'Orientation religieuses et culture islamique'),
	('01', 'Orientation religieuses'),
	('02', 'Culture islamique'),
	('03', 'Communication et coopération'),
	('04', 'Lieux de cultes'),
	('042', 'Formation et enseignement coranique'),
	('01', 'Formation et évaluation et recherche'),
	('02', 'Enseignement coranique'),
	('043', 'Administration générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien administratif'),
	('011', 'Education Nationale'),
	('044', 'Enseignement'),
	('01', 'Enseignement préparatoire et primaire'),
	('02', 'Enseignement moyen normal et spécifique et à distance'),
	('03', 'Enseignement secondaire normal, spécifique et à distance'),
	('046', 'Formation'),
	('01', 'Formation en cours d’emploi et Spécialisée'),
	('047', 'Vie scolaire et transferts sociaux'),
	('01', 'Vie scolaire'),
	('02', 'Transferts sociaux'),
	('048', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('012', 'Enseignement Supérieur et  Recherche Scientifique'),
	('049', 'Enseignement et formation supérieurs'),
	('01', '1er et 2ème cycles d’enseignement'),
	('02', 'Formation au 3ème  cycle'),
	('050', 'Recherche scientifique et développement technologique'),
	('01', 'Soutien administratif à la recherche et gestion des finances'),
	('02', 'Recherche et développement'),
	('03', 'Innovation technologique'),
	('051', 'Vie estudiantine'),
	('01', 'Œuvres universitaires'),
	('02', 'Conditions de vie des étudiants'),
	('052', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('013', 'Formation et Enseignement Professionnels'),
	('053', 'Formation Professionnelle'),
	('01', 'Formation Professionnelle initiale'),
	('02', 'Formation professionnelle continue et à distance'),
	('03', 'Ingénierie pédagogique de la Formation Professionnelle'),
	('054', 'Enseignement Professionnel'),
	('01', 'Enseignement Professionnel'),
	('02', 'Ingénierie pédagogique de l’Enseignement Professionnel'),
	('055', 'Administration Générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('014', 'Culture et Arts'),
	('056', 'Arts et Lettres'),
	('01', 'Livre et lecture publique'),
	('02', 'Création et diffusion du produit culturel  et artistique'),
	('057', 'Patrimoine culturel'),
	('01', 'Protection, valorisation et exploitation du patrimoine culturel'),
	('02', 'Restauration du patrimoine culturel'),
	('058', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('015', 'Sports'),
	('060', 'Sports'),
	('01', 'Jeunes talents, sports de l\'elite et de haut niveau'),
	('02', 'Promotion du sport pour tous et en milieux educatif et spécialisé'),
	('03', 'Vie associative, établissements sportifs et l\'éthique sportive'),
	('061', 'Administration Générale'),
	('01', 'Gestion du Ministere'),
	('02', 'Soutien administratif'),
	('017', 'Poste et Télécommunications'),
	('065', 'Développement des services postaux'),
	('01', 'Développement de l\'activité postale'),
	('02', 'Développement des services financiers postaux'),
	('066', 'Développement des télécommunications'),
	('01', 'Développement et la sécurisation des infrastructures des Technologies de l\'Information et de la Communication (TIC)'),
	('02', 'Développement des activités liées à la radiocommunication et des équipements sensibles des télécommunications'),
	('067', 'Edification de la société algérienne  de l\'information'),
	('01', 'Développement et promotion du contenu national, des services en ligne et généralisation des usages'),
	('02', 'Mise en place et la promotion d\'un environnement de confiance pour l’utilisation des nouvelles technologies'),
	('068', 'Administration Générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('018', 'Solidarité Nationale, Famille et Condition de la Femme'),
	('069', 'Personnes aux besoins spécifiques'),
	('01', 'Protection et insertion des personnes aux besoins spécifiques'),
	('02', 'Education et enseignement spécialisé des personnes aux besoins spécifiques'),
	('070', 'Famille et condition de la femme'),
	('01', 'Protection et promotion de la Famille et de la femme'),
	('02', 'Protection de l\'enfance et des personnes âgées'),
	('071', 'Développement social et Action humanitaire'),
	('01', 'Développement social'),
	('02', 'Mouvement associatif et Action humanitaire'),
	('072', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('019', 'Industrie et Production Pharmaceutique'),
	('073', 'Compétitivité et Développement Industriels'),
	('01', 'Compétitivité Industrielle'),
	('02', 'Développement Industriel'),
	('074', 'Appui à l\'investissement'),
	('01', 'Promotion de l\'Investissement'),
	('02', 'Appui à la PME'),
	('121', 'Développement et Promotion de l\'Industrie Pharmaceutique en Algerie'),
	('01', 'Développement et Promotion de l\'Industrie Pharmaceutique en Algerie'),
	('075', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien Administratif'),
	('020', 'Agriculture, Développement Rural et Pêche'),
	('076', 'Agriculture et Développement Rural'),
	('01', 'Développement de l\'agriculture'),
	('02', 'Sécurité et qualité sanitaires des aliments'),
	('03', 'Développement rural et gestion équilibrée et durable des territoires'),
	('077', 'Forêts'),
	('01', 'Gestion et soutien'),
	('02', 'Gestion durable et conservation du patrimoine'),
	('117', 'Pêche maritime'),
	('01', 'Développement des activités et des infrastructures liées à la Pêche'),
	('118', 'Aquaculture'),
	('01', 'Développement des activités et des infrastructures liées à l\'Aquaculture'),
	('119', 'Contrôle des actvités et de la qualité des produits de la pêche et de l\'aquaculture'),
	('01', 'Contrôle des activités de la Pêche et de l\'aquaculture et de la salubrité des milieux et des produits halieutiques'),
	('078', 'Administration Générale'),
	('01', 'Gestion du ministère'),
	('02', 'Gestion, intervention et soutien'),
	('021', 'Habitat, Urbanisme et Ville'),
	('079', 'Logement'),
	('01', 'Logement public locatif'),
	('02', 'Aides aux logement'),
	('080', 'Urbanisme et aménagement'),
	('01', 'Urbanisme'),
	('02', 'Aménagement du foncier'),
	('081', 'Villes et Villes nouvelles'),
	('01', 'Villes et Villes nouvelles'),
	('082', 'Equipements publics'),
	('01', 'Équipements publics de l\'éducation et de la formation'),
	('02', 'Équipements publics de sécurité et de santé'),
	('03', 'Autres publics équipements publics'),
	('083', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('022', 'Commerce Intérieur et Régulation du Marché National'),
	('084', 'Régulation et Promotion de la Concurrence'),
	('01', 'Régulation des Marchés'),
	('02', 'Organisation des Activités Commerciales'),
	('085', 'Protection du Consommateur'),
	('01', 'Analyse et contrôle de la qualité'),
	('02', 'Contrôle des Pratiques Commerciales'),
	('087', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien Administratif'),
	('023', 'Communication'),
	('088', 'Médias et Communication institutionnelle'),
	('01', 'Médias'),
	('02', 'Communication Institutionnelle'),
	('089', 'Administration Générale'),
	('01', 'Gestion Du Ministère'),
	('02', 'Soutien Administratif'),
	('024', 'Travaux Publics et Infrastructures de Base'),
	('090', 'Infrastructures routières et autoroutières'),
	('01', 'Développement des infrastructures routiéres'),
	('02', 'Entretien routier'),
	('03', 'Développement et entretien des autoroutes'),
	('091', 'Infrastructures aéroportuaires'),
	('01', 'Développements des infrastructures aéroportuaires'),
	('02', 'Maintenances des infrastructures aéroportuaires'),
	('092', 'Infrastructures maritimes'),
	('01', 'Développement des infrastructures maritimes'),
	('02', 'Maintenance des infrastructures maritimes et signalisation'),
	('142', 'Infrastructures ferroviaires et transports guidés'),
	('01', 'Développement des Infrastructures Ferroviaires'),
	('02', 'Développement des infrastructures de transports guidés'),
	('097', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('025', 'Transports'),
	('098', 'Mobilité et logistique'),
	('01', 'Transports routiers et logistique'),
	('02', 'Transports ferroviaires et guidés'),
	('099', 'Marine marchande et ports'),
	('01', 'Marine marchande'),
	('02', 'Ports'),
	('100', 'Aéronautique et météorologie'),
	('01', 'Aéronautique'),
	('02', 'Météorologie'),
	('101', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('026', 'Tourisme et Artisanat'),
	('102', 'Tourisme'),
	('01', 'Politique et promotion du  tourisme'),
	('02', 'Soutien aux projets touristiques'),
	('103', 'Artisanat et métiers'),
	('01', 'Pilotage et encadrement du développement de l’artisanat et des métiers'),
	('02', 'Promotion et amélioration des performances des acteurs'),
	('104', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('027', 'Santé'),
	('105', 'Prévention et soins'),
	('01', 'Prévention et soins'),
	('106', 'Formation dans le domaine de la santé'),
	('01', 'Formation et renforcement des compétences'),
	('107', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('028', 'Travail, Emploi et Sécurité Sociale'),
	('108', 'Inspection Générale du Travail'),
	('02', 'Gestion administrative et financière'),
	('01', 'Contrôle de l’application des dispositions  législatives et réglementaires du travail'),
	('109', 'Soutien et promotion de l’emploi'),
	('01', 'Accès au marché  de l’emploi'),
	('02', 'Dispositif d’emploi'),
	('110', 'Système de protection sociale'),
	('01', 'Mise en œuvre de la politique de sécurité sociale'),
	('02', 'Soutien au système de sécurité sociale'),
	('111', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('029', 'Relations avec le Parlement'),
	('112', 'Renforcement des relations entre le Gouvernement et le Parlement'),
	('01', 'Suivi du travail Parlementaire'),
	('02', 'Etude de textes législatifs et règlementaires'),
	('113', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('030', 'Environnement et Qualité de la Vie'),
	('114', 'Environnement et développement durable'),
	('01', 'Environnement urbain et industriel'),
	('02', 'Biodiversité et changement climatique'),
	('03', 'Education et sensibilisation environnementale'),
	('116', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien Administratif'),
	('033', 'Economie de la Connaissance, Start-up et Micro-Entreprises'),
	('123', 'Promotion de l\'économie de la connaissance, des startup et de l\'entrepreneuriat'),
	('01', 'Promotion  de l\'Economie de la Connaissance et des Startup'),
	('02', 'Promotion de l\'Entrepreneuriat et de la créativité'),
	('124', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien Administratif'),
	('051', 'Hydraulique'),
	('093', 'Mobilisation des ressources en eau et de la sécurité hydrique'),
	('01', 'Mobilisation des ressources en  eau Conventionnelles'),
	('02', 'Eau non conventionnelle'),
	('094', 'Approvisionnement en eau potable et industrielle'),
	('01', 'Adduction et Réseaux de distribution en eau potable et industrielle'),
	('095', 'Hydraulique agricole'),
	('01', 'Périmètres irrigués'),
	('02', 'Petite et moyenne hydraulique'),
	('096', 'Assainissement et protection du milieu naturel'),
	('01', 'Réseaux d\'assainissement et Systeme d\'épuration'),
	('02', 'Protection des villes contre les inondations'),
	('143', 'Administration générale'),
	('01', 'Gestion du ministère'),
	('02', 'Soutien administratif'),
	('052', 'Jeunesse'),
	('059', 'Jeunesse'),
	('01', 'Promotion de l\'animation socio-educative'),
	('02', 'Partenariat et établissements de jeunes'),
	('03', 'Tourisme et loisirs de jeunes'),
	('144', 'Administration Générale'),
	('01', 'Gestion du Ministere'),
	('02', 'Soutien administratif'),
	('053', 'Commerce Extérieur et Promotion des Exportations'),
	('086', 'Encadrement des Echanges Commerciaux et Promotion des Exportations'),
	('01', 'Echanges Commerciaux'),
	('02', 'Promotion des Exportations hors Hydrocarbures'),
	('145', 'Administration Générale'),
	('01', 'Gestion du Ministère'),
	('02', 'Soutien Administratif'),
	('500', 'Assemblée  Populaire  Nationale'),
	('125', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('00', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('501', 'Conseil de la Nation'),
	('126', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('00', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('505', 'Cour Constitutionnelle'),
	('130', 'Cour Constitutionnelle'),
	('00', 'Cour Constitutionnelle'),
	('502', 'Cour Suprême'),
	('127', 'Contrôle et évaluation des décisions judiciaires et l\'unification de la jurisprudence'),
	('01', 'Activité judiciaire'),
	('503', 'Conseil d\'Etat'),
	('128', 'Conseil d\'Etat'),
	('01', 'Régulation de l\'activité des juridictions administratives et compétences consultatives'),
	('02', 'Administration générale'),
	('504', 'Conseil Supérieur de la Magistrature'),
	('129', 'Indépendance de la justice'),
	('01', 'Gestion des sessions du Conseil'),
	('02', 'Administration générale'),
	('506', 'Cour des Comptes'),
	('131', 'Contrôle du patrimoine et des fonds publics'),
	('01', 'Vérification et jugement des comptes de gestion.'),
	('02', 'Contrôle de la qualité de gestion, de l’exécution de la loi de Finances et l’évaluation des programmes publics'),
	('03', 'Administration et  générale'),
	('507', 'Haute Autorité de Transparence, de Prévention et de Lutte Contre la Corruption'),
	('132', 'Prévention et lutte contre la corruption'),
	('02', 'Administration générale'),
	('01', 'Formation, sensibilisation, prévention et lutte contre la corruption'),
	('508', 'Autorité Nationale Indépendante des Elections'),
	('133', 'Préparation, organisation, gestion et supervision de l\'ensemble des opérations éléctorales et référendaires'),
	('01', 'Préparation de l\'ensemble des opérations éléctorales et référendaires'),
	('02', 'Organisation, gestion et supervision de l\'ensemble des opérations éléctorales et référendaires'),
	('03', 'Révision ordinaire des listes électorales'),
	('04', 'Administration et  générale'),
	('509', 'Conseil National Economique, Social et Environnemental'),
	('134', 'Dialogue ,  concertation et évaluation dans le domaine Economique, Social et Environnemental'),
	('01', 'Avis , recommandations et   élaboration des rapports et des études'),
	('02', 'Administration générale'),
	('510', 'Haut Conseil Islamique'),
	('135', 'Promotion des prescriptions religieuses islamiques'),
	('01', 'Encouragement et  promotion de l\'ijtihad'),
	('02', 'Administration et  générale'),
	('511', 'Haut Conseil de la Langue Arabe'),
	('136', 'Promotion et généralisation de la langue arabe'),
	('01', 'Activités du Haut Conseil de la Langue Arabe'),
	('02', 'Administration générale'),
	('512', 'Conseil National des Droits de l\'Homme'),
	('137', 'Droits de l\'Homme'),
	('01', 'Promotion et protection des droits de l’homme'),
	('02', 'Administration générale'),
	('513', 'Académie Algérienne des Sciences et des Technologies'),
	('138', 'Promouvoir le développement national durable par les sciences et les technologies'),
	('01', 'La consultation et l\'expertise dans le domaine des sciences et des technologies'),
	('02', 'Administration générale'),
	('514', 'Conseil National de la Recherche Scientifique et des Technologies'),
	('139', 'Développement de la recherche scientifique et technologique'),
	('01', 'Activité du Conseil'),
	('02', 'Administration générale'),
	('515', 'Observatoire National de la Société Civile'),
	('140', 'Promotion de la société civile.'),
	('01', 'Promotion de l\'Action de la société civile'),
	('02', 'Administration et  générale'),
	('516', 'Conseil Superieur de la Jeunesse'),
	('141', 'Promotion  de la jeunesse'),
	('01', 'Activités du Conseil'),
	('02', 'Administration et  générale');