CREATE TABLE "subprograms" (
    "code"	VARCHAR(512),
    "name"	VARCHAR(512)
);

INSERT INTO "subprograms" ("code", "name") VALUES
	('1', 'Supervision de l\'Activité Présidentielle'),
	('2', 'Sécurité et Protection'),
	('3', 'Archives et Mémoire Nationale'),
	('1', 'Coordination de l\'Activité Juridique et Gouvernementale'),
	('1', 'Médiation de la République'),
	('1', 'Promotion de la langue amazighe'),
	('1', 'Soutien Technique'),
	('2', 'Soutien Administratif'),
	('1', 'Gestion, coordination et suivi de l’activité du gouvernement'),
	('2', 'Soutien technique'),
	('1', 'Fonction publique'),
	('2', 'Réforme administrative'),
	('3', 'Soutien administratif'),
	('0', 'Défense Nationale'),
	('0', 'Logistique et soutien multiforme'),
	('0', 'Administration générale'),
	('1', 'Diplomatie et relations extérieures'),
	('2', 'Affaires consulaires et communauté nationale à l\'étranger'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Mouvement associatif et vie politique'),
	('2', 'Etat de circulation des personnes et des biens'),
	('3', 'Identité, titres et documents sécurisés'),
	('4', 'Numérisation du service public'),
	('1', 'Missions dévolues aux collectivités locales'),
	('2', 'Appui au développement socio-économique des collectivités locales'),
	('1', 'Instruments de l\'aménagement du territoire'),
	('2', 'Développement  et Attractivité du Territoire'),
	('1', 'Soutien administratif et logistique central et régional'),
	('2', 'Sécurité, ordre public, prévention  et intervention'),
	('3', 'Activités socio-professionnelles'),
	('1', 'Intervention et Prévention'),
	('2', 'Soutien administratif et logistique'),
	('1', 'Réseaux des transmissions'),
	('2', 'Soutien administratif et logistique'),
	('1', 'Soutient Administratif et logistique'),
	('2', 'Risques majeurs'),
	('3', 'Sécurité routière'),
	('1', 'Activité judiciaire ordinaire et administrative'),
	('2', 'Soutien administratif'),
	('3', 'Compte de la pension alimentaire '),
	('1', 'Conditions de détention'),
	('2', 'Réinsertion sociale'),
	('3', 'Sécurité'),
	('4', 'Soutien administratif'),
	('1', 'Stratégie, Appui technique et administratif'),
	('2', 'Investigations et recherches'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Gestion financière de l\'Etat'),
	('2', 'Modernisation des systèmes d\'information et instruments de paiement'),
	('3', 'Gestion comptable des opérations du trésor'),
	('4', 'Gestion des moyens et soutien administratif'),
	('1', 'Assiette, recouvrement et Contrôle fiscal'),
	('2', 'Soutien administratif'),
	('1', 'Elaboration et suivi du budget'),
	('2', 'Contrôle de la dépense'),
	('3', 'Soutien administratif'),
	('1', 'Gestion des Operations domaniales'),
	('2', 'Conservation et cadastre'),
	('3', 'Soutien administratif'),
	('1', 'Recouvrement douanier'),
	('2', 'Contrôles et Protection de l’Economie  nationale'),
	('3', 'Soutien administratif'),
	('1', 'Contrôle administratif des finances publiques  et des capitaux marchands de l\'Etat'),
	('2', 'Soutien administratif'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien administratif'),
	('0', 'Crédits non assignés'),
	('1', 'Electrification'),
	('2', 'Distribution publique du gaz'),
	('3', 'Programme spéciaux de l\'électricité et du gaz'),
	('4', 'Energies nouvelles'),
	('5', 'Soutien de l\'Etat à la facturation de l\'électricité'),
	('1', 'Mines et carrières'),
	('2', 'Ressources Minières'),
	('3', 'Développement minier'),
	('1', 'Compensation au titre du dessalement de l\'eau de mer'),
	('1', 'Maitrise de l\'Energie'),
	('2', 'Energies Renouvelables'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien administratif'),
	('1', 'Protection des symboles et des hauts -fait historique'),
	('2', 'Recherche historique et suivi des activités muséales'),
	('1', 'Invalides et recours'),
	('2', 'Ayants droit'),
	('1', 'Santé des Moudjahidine et ayants droit'),
	('2', 'Promotion sociale'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Orientation religieuses'),
	('2', 'Culture islamique'),
	('3', 'Communication et coopération'),
	('4', 'Lieux de cultes'),
	('1', 'Formation et évaluation et recherche'),
	('2', 'Enseignement coranique'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien administratif'),
	('1', 'Enseignement préparatoire et primaire'),
	('2', 'Enseignement moyen normal et spécifique et à distance'),
	('3', 'Enseignement secondaire normal, spécifique et à distance'),
	('1', 'Formation en cours d’emploi et Spécialisée'),
	('1', 'Vie scolaire'),
	('2', 'Transferts sociaux'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', '1er et 2ème cycles d’enseignement'),
	('2', 'Formation au 3ème  cycle'),
	('1', 'Soutien administratif à la recherche et gestion des finances'),
	('2', 'Recherche et développement'),
	('3', 'Innovation technologique'),
	('1', 'Œuvres universitaires'),
	('2', 'Conditions de vie des étudiants'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Formation Professionnelle initiale'),
	('2', 'Formation professionnelle continue et à distance'),
	('3', 'Ingénierie pédagogique de la Formation Professionnelle'),
	('1', 'Enseignement Professionnel'),
	('2', 'Ingénierie pédagogique de l’Enseignement Professionnel'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Livre et lecture publique'),
	('2', 'Création et diffusion du produit culturel  et artistique'),
	('1', 'Protection, valorisation et exploitation du patrimoine culturel'),
	('2', 'Restauration du patrimoine culturel'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Jeunes talents, sports de l\'elite et de haut niveau'),
	('2', 'Promotion du sport pour tous et en milieux educatif et spécialisé'),
	('3', 'Vie associative, établissements sportifs et l\'éthique sportive'),
	('1', 'Gestion du Ministere'),
	('2', 'Soutien administratif'),
	('1', 'Développement de l\'activité postale'),
	('2', 'Développement des services financiers postaux'),
	('1', 'Développement et la sécurisation des infrastructures des Technologies de l\'Information et de la Communication (TIC)'),
	('2', 'Développement des activités liées à la radiocommunication et des équipements sensibles des télécommunications'),
	('1', 'Développement et promotion du contenu national, des services en ligne et généralisation des usages'),
	('2', 'Mise en place et la promotion d\'un environnement de confiance pour l’utilisation des nouvelles technologies'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Protection et insertion des personnes aux besoins spécifiques'),
	('2', 'Education et enseignement spécialisé des personnes aux besoins spécifiques'),
	('1', 'Protection et promotion de la Famille et de la femme'),
	('2', 'Protection de l\'enfance et des personnes âgées'),
	('1', 'Développement social'),
	('2', 'Mouvement associatif et Action humanitaire'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Compétitivité Industrielle'),
	('2', 'Développement Industriel'),
	('1', 'Promotion de l\'Investissement'),
	('2', 'Appui à la PME'),
	('1', 'Développement et Promotion de l\'Industrie Pharmaceutique en Algerie'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien Administratif'),
	('1', 'Développement de l\'agriculture'),
	('2', 'Sécurité et qualité sanitaires des aliments'),
	('3', 'Développement rural et gestion équilibrée et durable des territoires'),
	('1', 'Gestion et soutien'),
	('2', 'Gestion durable et conservation du patrimoine'),
	('1', 'Développement des activités et des infrastructures liées à la Pêche'),
	('1', 'Développement des activités et des infrastructures liées à l\'Aquaculture'),
	('1', 'Contrôle des activités de la Pêche et de l\'aquaculture et de la salubrité des milieux et des produits halieutiques'),
	('1', 'Gestion du ministère'),
	('2', 'Gestion, intervention et soutien'),
	('1', 'Logement public locatif'),
	('2', 'Aides aux logement'),
	('1', 'Urbanisme'),
	('2', 'Aménagement du foncier'),
	('1', 'Villes et Villes nouvelles'),
	('1', 'Équipements publics de l\'éducation et de la formation'),
	('2', 'Équipements publics de sécurité et de santé'),
	('3', 'Autres publics équipements publics'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Régulation des Marchés'),
	('2', 'Organisation des Activités Commerciales'),
	('1', 'Analyse et contrôle de la qualité'),
	('2', 'Contrôle des Pratiques Commerciales'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien Administratif'),
	('1', 'Médias'),
	('2', 'Communication Institutionnelle'),
	('1', 'Gestion Du Ministère'),
	('2', 'Soutien Administratif'),
	('1', 'Développement des infrastructures routiéres'),
	('2', 'Entretien routier'),
	('3', 'Développement et entretien des autoroutes'),
	('1', 'Développements des infrastructures aéroportuaires'),
	('2', 'Maintenances des infrastructures aéroportuaires'),
	('1', 'Développement des infrastructures maritimes'),
	('2', 'Maintenance des infrastructures maritimes et signalisation'),
	('1', 'Développement des Infrastructures Ferroviaires'),
	('2', 'Développement des infrastructures de transports guidés'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Transports routiers et logistique'),
	('2', 'Transports ferroviaires et guidés'),
	('1', 'Marine marchande'),
	('2', 'Ports'),
	('1', 'Aéronautique'),
	('2', 'Météorologie'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Politique et promotion du  tourisme'),
	('2', 'Soutien aux projets touristiques'),
	('1', 'Pilotage et encadrement du développement de l’artisanat et des métiers'),
	('2', 'Promotion et amélioration des performances des acteurs'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Prévention et soins'),
	('1', 'Formation et renforcement des compétences'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('2', 'Gestion administrative et financière'),
	('1', 'Contrôle de l’application des dispositions  législatives et réglementaires du travail'),
	('1', 'Accès au marché  de l’emploi'),
	('2', 'Dispositif d’emploi'),
	('1', 'Mise en œuvre de la politique de sécurité sociale'),
	('2', 'Soutien au système de sécurité sociale'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Suivi du travail Parlementaire'),
	('2', 'Etude de textes législatifs et règlementaires'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Environnement urbain et industriel'),
	('2', 'Biodiversité et changement climatique'),
	('3', 'Education et sensibilisation environnementale'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien Administratif'),
	('1', 'Promotion  de l\'Economie de la Connaissance et des Startup'),
	('2', 'Promotion de l\'Entrepreneuriat et de la créativité'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien Administratif'),
	('1', 'Mobilisation des ressources en  eau Conventionnelles'),
	('2', 'Eau non conventionnelle'),
	('1', 'Adduction et Réseaux de distribution en eau potable et industrielle'),
	('1', 'Périmètres irrigués'),
	('2', 'Petite et moyenne hydraulique'),
	('1', 'Réseaux d\'assainissement et Systeme d\'épuration'),
	('2', 'Protection des villes contre les inondations'),
	('1', 'Gestion du ministère'),
	('2', 'Soutien administratif'),
	('1', 'Promotion de l\'animation socio-educative'),
	('2', 'Partenariat et établissements de jeunes'),
	('3', 'Tourisme et loisirs de jeunes'),
	('1', 'Gestion du Ministere'),
	('2', 'Soutien administratif'),
	('1', 'Echanges Commerciaux'),
	('2', 'Promotion des Exportations hors Hydrocarbures'),
	('1', 'Gestion du Ministère'),
	('2', 'Soutien Administratif'),
	('', 'S/Total Portefeuilles de Programmes \'Ministères\''),
	('0', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('0', 'Législation et contrôle de l\'Action du Gouvernement.'),
	('0', 'Cour Constitutionnelle'),
	('', 'S/Total Portefeuilles de Dotations'),
	('1', 'Activité judiciaire'),
	('1', 'Régulation de l\'activité des juridictions administratives et compétences consultatives'),
	('2', 'Administration générale'),
	('1', 'Gestion des sessions du Conseil'),
	('2', 'Administration générale'),
	('1', 'Vérification et jugement des comptes de gestion.'),
	('2', 'Contrôle de la qualité de gestion, de l’exécution de la loi de Finances et l’évaluation des programmes publics'),
	('3', 'Administration et  générale'),
	('2', 'Administration générale'),
	('1', 'Formation, sensibilisation, prévention et lutte contre la corruption'),
	('1', 'Préparation de l\'ensemble des opérations éléctorales et référendaires'),
	('2', 'Organisation, gestion et supervision de l\'ensemble des opérations éléctorales et référendaires'),
	('3', 'Révision ordinaire des listes électorales'),
	('4', 'Administration et  générale'),
	('1', 'Avis , recommandations et   élaboration des rapports et des études'),
	('2', 'Administration générale'),
	('1', 'Encouragement et  promotion de l\'ijtihad'),
	('2', 'Administration et  générale'),
	('1', 'Activités du Haut Conseil de la Langue Arabe'),
	('2', 'Administration générale'),
	('1', 'Promotion et protection des droits de l’homme'),
	('2', 'Administration générale'),
	('1', 'La consultation et l\'expertise dans le domaine des sciences et des technologies'),
	('2', 'Administration générale'),
	('1', 'Activité du Conseil'),
	('2', 'Administration générale'),
	('1', 'Promotion de l\'Action de la société civile'),
	('2', 'Administration et  générale'),
	('1', 'Activités du Conseil'),
	('2', 'Administration et  générale');