-- 5. Subprograms
CREATE TABLE IF NOT EXISTS programs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    objectives TEXT[],
    expected_results TEXT[],
    performance_indicators JSONB,
    code VARCHAR(20),
    type VARCHAR(20) CHECK (type IN ('program', 'subprogram')),
    parent_id UUID REFERENCES programs(id),
    allocated_ae NUMERIC,
    allocated_cp NUMERIC,
    status TEXT CHECK (status IN ('draft', 'active', 'archived')) DEFAULT 'draft'
);

INSERT INTO programs (name, code, type, status) VALUES
    ('Supervision de l''Activité Présidentielle', 'PRG-001-01', 'subprogram', 'active'),
    ('Sécurité et Protection', 'PRG-001-02', 'subprogram', 'active'),
    ('Archives et Mémoire Nationale', 'PRG-001-03', 'subprogram', 'active'),
    ('Coordination de l''Activité Juridique et Gouvernementale', 'PRG-002-01', 'subprogram', 'active'),
    ('Médiation de la République', 'PRG-003-01', 'subprogram', 'active'),
    ('Promotion de la langue amazighe', 'PRG-004-01', 'subprogram', 'active'),
    ('Soutien Technique', 'PRG-005-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-005-02', 'subprogram', 'active'),
    ('Gestion, coordination et suivi de l''activité du gouvernement', 'PRG-006-01', 'subprogram', 'active'),
    ('Soutien technique', 'PRG-006-02', 'subprogram', 'active'),
    ('Fonction publique', 'PRG-008-01', 'subprogram', 'active'),
    ('Réforme administrative', 'PRG-008-02', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-008-03', 'subprogram', 'active'),
    ('Défense Nationale', 'PRG-009-00', 'subprogram', 'active'),
    ('Logistique et soutien multiforme', 'PRG-010-00', 'subprogram', 'active'),
    ('Administration générale', 'PRG-011-00', 'subprogram', 'active'),
    ('Diplomatie et relations extérieures', 'PRG-012-01', 'subprogram', 'active'),
    ('Affaires consulaires et communauté nationale à l''étranger', 'PRG-012-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-013-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-013-02', 'subprogram', 'active'),
    ('Mouvement associatif et vie politique', 'PRG-014-01', 'subprogram', 'active'),
    ('État de circulation des personnes et des biens', 'PRG-014-02', 'subprogram', 'active'),
    ('Identité, titres et documents sécurisés', 'PRG-014-03', 'subprogram', 'active'),
    ('Numérisation du service public', 'PRG-014-04', 'subprogram', 'active'),
    ('Missions dévolues aux collectivités locales', 'PRG-015-01', 'subprogram', 'active'),
    ('Appui au développement socio-économique des collectivités locales', 'PRG-015-02', 'subprogram', 'active'),
    ('Instruments de l''aménagement du territoire', 'PRG-016-01', 'subprogram', 'active'),
    ('Développement et Attractivité du Territoire', 'PRG-016-02', 'subprogram', 'active'),
    ('Soutien administratif et logistique central et régional', 'PRG-017-01', 'subprogram', 'active'),
    ('Sécurité, ordre public, prévention et intervention', 'PRG-017-02', 'subprogram', 'active'),
    ('Activités socio-professionnelles', 'PRG-017-03', 'subprogram', 'active'),
    ('Intervention et Prévention', 'PRG-018-01', 'subprogram', 'active'),
    ('Soutien administratif et logistique', 'PRG-018-02', 'subprogram', 'active'),
    ('Réseaux des transmissions', 'PRG-019-01', 'subprogram', 'active'),
    ('Soutien administratif et logistique', 'PRG-019-02', 'subprogram', 'active'),
    ('Soutient Administratif et logistique', 'PRG-020-01', 'subprogram', 'active'),
    ('Risques majeurs', 'PRG-020-02', 'subprogram', 'active'),
    ('Sécurité routière', 'PRG-020-03', 'subprogram', 'active'),
    ('Activité judiciaire ordinaire et administrative', 'PRG-021-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-021-02', 'subprogram', 'active'),
    ('Compte de la pension alimentaire', 'PRG-021-03', 'subprogram', 'active'),
    ('Conditions de détention', 'PRG-022-01', 'subprogram', 'active'),
    ('Réinsertion sociale', 'PRG-022-02', 'subprogram', 'active'),
    ('Sécurité', 'PRG-022-03', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-022-04', 'subprogram', 'active'),
    ('Stratégie, Appui technique et administratif', 'PRG-023-01', 'subprogram', 'active'),
    ('Investigations et recherches', 'PRG-023-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-024-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-024-02', 'subprogram', 'active'),
    ('Gestion financière de l''État', 'PRG-025-01', 'subprogram', 'active'),
    ('Modernisation des systèmes d''information et instruments de paiement', 'PRG-025-02', 'subprogram', 'active'),
    ('Gestion comptable des opérations du trésor', 'PRG-025-03', 'subprogram', 'active'),
    ('Gestion des moyens et soutien administratif', 'PRG-025-04', 'subprogram', 'active'),
    ('Assiette, recouvrement et Contrôle fiscal', 'PRG-026-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-026-02', 'subprogram', 'active'),
    ('Elaboration et suivi du budget', 'PRG-027-01', 'subprogram', 'active'),
    ('Contrôle de la dépense', 'PRG-027-02', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-027-03', 'subprogram', 'active'),
    ('Gestion des Operations domaniales', 'PRG-028-01', 'subprogram', 'active'),
    ('Conservation et cadastre', 'PRG-028-02', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-028-03', 'subprogram', 'active'),
    ('Recouvrement douanier', 'PRG-029-01', 'subprogram', 'active'),
    ('Contrôles et Protection de l''Économie nationale', 'PRG-029-02', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-029-03', 'subprogram', 'active'),
    ('Contrôle administratif des finances publiques et des capitaux marchands de l''État', 'PRG-030-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-030-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-031-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-031-02', 'subprogram', 'active'),
    ('Crédits non assignés', 'PRG-700-00', 'subprogram', 'active'),
    ('Electrification', 'PRG-032-01', 'subprogram', 'active'),
    ('Distribution publique du gaz', 'PRG-032-02', 'subprogram', 'active'),
    ('Programme spéciaux de l''électricité et du gaz', 'PRG-032-03', 'subprogram', 'active'),
    ('Energies nouvelles', 'PRG-032-04', 'subprogram', 'active'),
    ('Soutien de l''État à la facturation de l''électricité', 'PRG-032-05', 'subprogram', 'active'),
    ('Mines et carrières', 'PRG-033-01', 'subprogram', 'active'),
    ('Ressources Minières', 'PRG-033-02', 'subprogram', 'active'),
    ('Développement minier', 'PRG-033-03', 'subprogram', 'active'),
    ('Compensation au titre du dessalement de l''eau de mer', 'PRG-034-01', 'subprogram', 'active'),
    ('Maîtrise de l''Energie', 'PRG-035-01', 'subprogram', 'active'),
    ('Energies Renouvelables', 'PRG-035-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-036-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-036-02', 'subprogram', 'active'),
    ('Protection des symboles et des hauts-fait historique', 'PRG-037-01', 'subprogram', 'active'),
    ('Recherche historique et suivi des activités muséales', 'PRG-037-02', 'subprogram', 'active'),
    ('Invalides et recours', 'PRG-038-01', 'subprogram', 'active'),
    ('Ayants droit', 'PRG-038-02', 'subprogram', 'active'),
    ('Santé des Moudjahidin et ayants droit', 'PRG-039-01', 'subprogram', 'active'),
    ('Promotion sociale', 'PRG-039-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-040-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-040-02', 'subprogram', 'active'),
    ('Orientation religieuses', 'PRG-041-01', 'subprogram', 'active'),
    ('Culture islamique', 'PRG-041-02', 'subprogram', 'active'),
    ('Communication et coopération', 'PRG-041-03', 'subprogram', 'active'),
    ('Lieux de cultes', 'PRG-041-04', 'subprogram', 'active'),
    ('Formation et évaluation et recherche', 'PRG-042-01', 'subprogram', 'active'),
    ('Enseignement coranique', 'PRG-042-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-043-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-043-02', 'subprogram', 'active'),
    ('Enseignement préparatoire et primaire', 'PRG-044-01', 'subprogram', 'active'),
    ('Enseignement moyen normal et spécifique et à distance', 'PRG-044-02', 'subprogram', 'active'),
    ('Enseignement secondaire normal, spécifique et à distance', 'PRG-044-03', 'subprogram', 'active'),
    ('Formation en cours d''emploi et Spécialisée', 'PRG-046-01', 'subprogram', 'active'),
    ('Vie scolaire', 'PRG-047-01', 'subprogram', 'active'),
    ('Transferts sociaux', 'PRG-047-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-048-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-048-02', 'subprogram', 'active'),
    ('1er et 2ème cycles d''enseignement', 'PRG-049-01', 'subprogram', 'active'),
    ('Formation au 3ème cycle', 'PRG-049-02', 'subprogram', 'active'),
    ('Soutien administratif à la recherche et gestion des finances', 'PRG-050-01', 'subprogram', 'active'),
    ('Recherche et développement', 'PRG-050-02', 'subprogram', 'active'),
    ('Innovation technologique', 'PRG-050-03', 'subprogram', 'active'),
    ('Œuvres universitaires', 'PRG-051-01', 'subprogram', 'active'),
    ('Conditions de vie des étudiants', 'PRG-051-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-052-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-052-02', 'subprogram', 'active'),
    ('Formation Professionnelle initiale', 'PRG-053-01', 'subprogram', 'active'),
    ('Formation professionnelle continue et à distance', 'PRG-053-02', 'subprogram', 'active'),
    ('Ingénierie pédagogique de la Formation Professionnelle', 'PRG-053-03', 'subprogram', 'active'),
    ('Enseignement Professionnel', 'PRG-054-01', 'subprogram', 'active'),
    ('Ingénierie pédagogique de l''Enseignement Professionnel', 'PRG-054-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-055-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-055-02', 'subprogram', 'active'),
    ('Livre et lecture publique', 'PRG-056-01', 'subprogram', 'active'),
    ('Création et diffusion du produit culturel et artistique', 'PRG-056-02', 'subprogram', 'active'),
    ('Protection, valorisation et exploitation du patrimoine culturel', 'PRG-057-01', 'subprogram', 'active'),
    ('Restauration du patrimoine culturel', 'PRG-057-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-058-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-058-02', 'subprogram', 'active'),
    ('Jeunes talents, sports de l''elite et de haut niveau', 'PRG-060-01', 'subprogram', 'active'),
    ('Promotion du sport pour tous et en milieux éducatif et spécialisé', 'PRG-060-02', 'subprogram', 'active'),
    ('Vie associative, établissements sportifs et l''éthique sportive', 'PRG-060-03', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-061-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-061-02', 'subprogram', 'active'),
    ('Développement de l''activité postale', 'PRG-065-01', 'subprogram', 'active'),
    ('Développement des services financiers postaux', 'PRG-065-02', 'subprogram', 'active'),
    ('Développement et la sécurisation des infrastructures des Technologies de l''Information et de la Communication (TIC)', 'PRG-066-01', 'subprogram', 'active'),
    ('Développement des activités liées à la radiocommunication et des équipements sensibles des télécommunications', 'PRG-066-02', 'subprogram', 'active'),
    ('Développement et promotion du contenu national, des services en ligne et généralisation des usages', 'PRG-067-01', 'subprogram', 'active'),
    ('Mise en place et la promotion d''un environnement de confiance pour l''utilisation des nouvelles technologies', 'PRG-067-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-068-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-068-02', 'subprogram', 'active'),
    ('Protection et insertion des personnes aux besoins spécifiques', 'PRG-069-01', 'subprogram', 'active'),
    ('Education et enseignement spécialisé des personnes aux besoins spécifiques', 'PRG-069-02', 'subprogram', 'active'),
    ('Protection et promotion de la Famille et de la femme', 'PRG-070-01', 'subprogram', 'active'),
    ('Protection de l''enfance et des personnes âgées', 'PRG-070-02', 'subprogram', 'active'),
    ('Développement social', 'PRG-071-01', 'subprogram', 'active'),
    ('Mouvement associatif et Action humanitaire', 'PRG-071-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-072-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-072-02', 'subprogram', 'active'),
    ('Compétitivité Industrielle', 'PRG-073-01', 'subprogram', 'active'),
    ('Développement Industriel', 'PRG-073-02', 'subprogram', 'active'),
    ('Promotion de l''Investissement', 'PRG-074-01', 'subprogram', 'active'),
    ('Appui à la PME', 'PRG-074-02', 'subprogram', 'active'),
    ('Développement et Promotion de l''Industrie Pharmaceutique en Algérie', 'PRG-121-01', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-075-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-075-02', 'subprogram', 'active'),
    ('Développement de l''agriculture', 'PRG-076-01', 'subprogram', 'active'),
    ('Sécurité et qualité sanitaires des aliments', 'PRG-076-02', 'subprogram', 'active'),
    ('Développement rural et gestion équilibrée et durable des territoires', 'PRG-076-03', 'subprogram', 'active'),
    ('Gestion et soutien', 'PRG-077-01', 'subprogram', 'active'),
    ('Gestion durable et conservation du patrimoine', 'PRG-077-02', 'subprogram', 'active'),
    ('Développement des activités et des infrastructures liées à la Pêche', 'PRG-117-01', 'subprogram', 'active'),
    ('Développement des activités et des infrastructures liées à l''Aquaculture', 'PRG-118-01', 'subprogram', 'active'),
    ('Contrôle des activités de la Pêche et de l''aquaculture et de la salubrité des milieux et des produits halieutiques', 'PRG-119-01', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-078-01', 'subprogram', 'active'),
    ('Gestion, intervention et soutien', 'PRG-078-02', 'subprogram', 'active'),
    ('Logement public locatif', 'PRG-079-01', 'subprogram', 'active'),
    ('Aides aux logement', 'PRG-079-02', 'subprogram', 'active'),
    ('Urbanisme', 'PRG-080-01', 'subprogram', 'active'),
    ('Aménagement du foncier', 'PRG-080-02', 'subprogram', 'active'),
    ('Villes et Villes nouvelles', 'PRG-081-01', 'subprogram', 'active'),
    ('Équipements publics de l''éducation et de la formation', 'PRG-082-01', 'subprogram', 'active'),
    ('Équipements publics de sécurité et de santé', 'PRG-082-02', 'subprogram', 'active'),
    ('Autres publics équipements publics', 'PRG-082-03', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-083-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-083-02', 'subprogram', 'active'),
    ('Régulation des Marchés', 'PRG-084-01', 'subprogram', 'active'),
    ('Organisation des Activités Commerciales', 'PRG-084-02', 'subprogram', 'active'),
    ('Analyse et contrôle de la qualité', 'PRG-085-01', 'subprogram', 'active'),
    ('Contrôle des Pratiques Commerciales', 'PRG-085-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-087-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-087-02', 'subprogram', 'active'),
    ('Médias', 'PRG-088-01', 'subprogram', 'active'),
    ('Communication Institutionnelle', 'PRG-088-02', 'subprogram', 'active'),
    ('Gestion Du Ministère', 'PRG-089-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-089-02', 'subprogram', 'active'),
    ('Développement des infrastructures routières', 'PRG-090-01', 'subprogram', 'active'),
    ('Entretien routier', 'PRG-090-02', 'subprogram', 'active'),
    ('Développement et entretien des autoroutes', 'PRG-090-03', 'subprogram', 'active'),
    ('Développements des infrastructures aéroportuaires', 'PRG-091-01', 'subprogram', 'active'),
    ('Maintenances des infrastructures aéroportuaires', 'PRG-091-02', 'subprogram', 'active'),
    ('Développement des infrastructures maritimes', 'PRG-092-01', 'subprogram', 'active'),
    ('Maintenance des infrastructures maritimes et signalisation', 'PRG-092-02', 'subprogram', 'active'),
    ('Développement des Infrastructures Ferroviaires', 'PRG-142-01', 'subprogram', 'active'),
    ('Développement des infrastructures de transports guidés', 'PRG-142-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-097-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-097-02', 'subprogram', 'active'),
    ('Transports routiers et logistique', 'PRG-098-01', 'subprogram', 'active'),
    ('Transports ferroviaires et guidés', 'PRG-098-02', 'subprogram', 'active'),
    ('Marine marchande', 'PRG-099-01', 'subprogram', 'active'),
    ('Ports', 'PRG-099-02', 'subprogram', 'active'),
    ('Aéronautique', 'PRG-100-01', 'subprogram', 'active'),
    ('Météorologie', 'PRG-100-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-101-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-101-02', 'subprogram', 'active'),
    ('Politique et promotion du tourisme', 'PRG-102-01', 'subprogram', 'active'),
    ('Soutien aux projets touristiques', 'PRG-102-02', 'subprogram', 'active'),
    ('Pilotage et encadrement du développement de l''artisanat et des métiers', 'PRG-103-01', 'subprogram', 'active'),
    ('Promotion et amélioration des performances des acteurs', 'PRG-103-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-104-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-104-02', 'subprogram', 'active'),
    ('Prévention et soins', 'PRG-105-01', 'subprogram', 'active'),
    ('Formation et renforcement des compétences', 'PRG-106-01', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-107-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-107-02', 'subprogram', 'active'),
    ('Contrôle de l''application des dispositions législatives et réglementaires du travail', 'PRG-108-01', 'subprogram', 'active'),
    ('Gestion administrative et financière', 'PRG-108-02', 'subprogram', 'active'),
    ('Accès au marché de l''emploi', 'PRG-109-01', 'subprogram', 'active'),
    ('Dispositif d''emploi', 'PRG-109-02', 'subprogram', 'active'),
    ('Mise en œuvre de la politique de sécurité sociale', 'PRG-110-01', 'subprogram', 'active'),
    ('Soutien au système de sécurité sociale', 'PRG-110-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-111-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-111-02', 'subprogram', 'active'),
    ('Suivi du travail Parlementaire', 'PRG-112-01', 'subprogram', 'active'),
    ('Etude de textes législatifs et réglementaires', 'PRG-112-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-113-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-113-02', 'subprogram', 'active'),
    ('Environnement urbain et industriel', 'PRG-114-01', 'subprogram', 'active'),
    ('Biodiversité et changement climatique', 'PRG-114-02', 'subprogram', 'active'),
    ('Education et sensibilisation environnementale', 'PRG-114-03', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-116-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-116-02', 'subprogram', 'active'),
    ('Promotion de l''Économie de la Connaissance et des Startup', 'PRG-123-01', 'subprogram', 'active'),
    ('Promotion de l''Entrepreneuriat et de la créativité', 'PRG-123-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-124-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-124-02', 'subprogram', 'active'),
    ('Mobilisation des ressources en eau Conventionnelles', 'PRG-093-01', 'subprogram', 'active'),
    ('Eau non conventionnelle', 'PRG-093-02', 'subprogram', 'active'),
    ('Adduction et Réseaux de distribution en eau potable et industrielle', 'PRG-094-01', 'subprogram', 'active'),
    ('Périmètres irrigués', 'PRG-095-01', 'subprogram', 'active'),
    ('Petite et moyenne hydraulique', 'PRG-095-02', 'subprogram', 'active'),
    ('Réseaux d''assainissement et Système d''épuration', 'PRG-096-01', 'subprogram', 'active'),
    ('Protection des villes contre les inondations', 'PRG-096-02', 'subprogram', 'active'),
    ('Gestion du ministère', 'PRG-143-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-143-02', 'subprogram', 'active'),
    ('Promotion de l''animation socio-educative', 'PRG-059-01', 'subprogram', 'active'),
    ('Partenariat et établissements de jeunes', 'PRG-059-02', 'subprogram', 'active'),
    ('Tourisme et loisirs de jeunes', 'PRG-059-03', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-144-01', 'subprogram', 'active'),
    ('Soutien administratif', 'PRG-144-02', 'subprogram', 'active'),
    ('Échanges Commerciaux', 'PRG-086-01', 'subprogram', 'active'),
    ('Promotion des Exportations hors Hydrocarbures', 'PRG-086-02', 'subprogram', 'active'),
    ('Gestion du Ministère', 'PRG-145-01', 'subprogram', 'active'),
    ('Soutien Administratif', 'PRG-145-02', 'subprogram', 'active'),
    ('Législation et contrôle de l''Action du Gouvernement.', 'PRG-125-00', 'subprogram', 'active'),
    ('Législation et contrôle de l''Action du Gouvernement.', 'PRG-126-00', 'subprogram', 'active'),
    ('Cour Constitutionnelle', 'PRG-130-00', 'subprogram', 'active'),
    ('Activité judiciaire', 'PRG-127-01', 'subprogram', 'active'),
    ('Régulation de l''activité des juridictions administratives et compétences consultatives', 'PRG-128-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-128-02', 'subprogram', 'active'),
    ('Gestion des sessions du Conseil', 'PRG-129-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-129-02', 'subprogram', 'active'),
    ('Vérification et jugement des comptes de gestion.', 'PRG-131-01', 'subprogram', 'active'),
    ('Contrôle de la qualité de gestion, de l''exécution de la loi de Finances et l''évaluation des programmes publics', 'PRG-131-02', 'subprogram', 'active'),
    ('Administration et générale', 'PRG-131-03', 'subprogram', 'active'),
    ('Formation, sensibilisation, prévention et lutte contre la corruption', 'PRG-132-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-132-02', 'subprogram', 'active'),
    ('Préparation de l''ensemble des opérations électorales et référendaires', 'PRG-133-01', 'subprogram', 'active'),
    ('Organisation, gestion et supervision de l''ensemble des opérations électorales et référendaires', 'PRG-133-02', 'subprogram', 'active'),
    ('Révision ordinaire des listes électorales', 'PRG-133-03', 'subprogram', 'active'),
    ('Administration et générale', 'PRG-133-04', 'subprogram', 'active'),
    ('Avis, recommandations et élaboration des rapports et des études', 'PRG-134-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-134-02', 'subprogram', 'active'),
    ('Encouragement et promotion de l''ijtihad', 'PRG-135-01', 'subprogram', 'active'),
    ('Administration et générale', 'PRG-135-02', 'subprogram', 'active'),
    ('Activités du Haut Conseil de la Langue Arabe', 'PRG-136-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-136-02', 'subprogram', 'active'),
    ('Promotion et protection des droits de l''homme', 'PRG-137-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-137-02', 'subprogram', 'active'),
    ('La consultation et l''expertise dans le domaine des sciences et des technologies', 'PRG-138-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-138-02', 'subprogram', 'active'),
    ('Activité du Conseil', 'PRG-139-01', 'subprogram', 'active'),
    ('Administration générale', 'PRG-139-02', 'subprogram', 'active'),
    ('Promotion de l''Action de la société civile', 'PRG-140-01', 'subprogram', 'active'),
    ('Administration et générale', 'PRG-140-02', 'subprogram', 'active'),
    ('Activités du Conseil', 'PRG-141-01', 'subprogram', 'active'),
    ('Administration et générale', 'PRG-141-02', 'subprogram', 'active');