-- 7. Wilayas
CREATE TABLE IF NOT EXISTS wilayas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(10),
    name_ar TEXT NOT NULL,
    name_en TEXT,
    name_fr TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    parent_id UUID REFERENCES wilayas(id),
    description TEXT
);

INSERT INTO "Wilayas" ("code", "name_fr", "name_ar", "name_en") VALUES
	('01', 'Adrar', 'أدرار', 'Adrar'),
	('02', 'Chlef', 'الشلف', 'Chlef'),
	('03', 'Laghouat', 'الأغواط', 'Laghouat'),
	('04', 'Oum El Bouaghi', 'أم البواقي', 'Oum El Bouaghi'),
	('05', 'Batna', 'باتنة', 'Batna'),
	('06', 'Beajaia', 'بجاية', 'Bejaia'),
	('07', 'Biskra', 'بسكرة', 'Biskra'),
	('08', 'Bechar', 'بشار', 'Bechar'),
	('09', 'Blida', 'البليدة', 'Blida'),
	('10', 'Bouira', 'البويرة', 'Bouira'),
	('11', 'Tamenrasset', 'تمنراست', 'Tamanrasset'),
	('12', 'Tebessa', 'تبسة', 'Tebessa'),
	('13', 'Tlemcen', 'تلمسان', 'Tlemcen'),
	('14', 'Tiaret', 'تيارت', 'Tiaret'),
	('15', 'Tizi Ouzou', 'تيزي وزو', 'Tizi Ouzou'),
	('16', 'Alger', 'الجزائر', 'Algiers'),
	('17', 'Djelfa', 'الجلفة', 'Djelfa'),
	('18', 'Jijel', 'جيجل', 'Jijel'),
	('19', 'Setif', 'سطيف', 'Setif'),
	('20', 'Saida', 'سعيدة', 'Saida'),
	('21', 'Skikda', 'سكيكدة', 'Skikda'),
	('22', 'Sidi Bel Abbes', 'سيدي بلعباس', 'Sidi Bel Abbes'),
	('23', 'Annaba', 'عنابة', 'Annaba'),
	('24', 'Guelma', 'قالمة', 'Guelma'),
	('25', 'Constantine', 'قسنطينة', 'Constantine'),
	('26', 'Medea', 'المدية', 'Medea'),
	('27', 'Mostaganem', 'مستغانم', 'Mostaganem'),
	('28', 'M''sila', 'المسيلة', 'M''sila'),
	('29', 'Mascara', 'معسكر', 'Mascara'),
	('30', 'Ouargla', 'ورقلة', 'Ouargla'),
	('31', 'Oran', 'وهران', 'Oran'),
	('32', 'El bayadh', 'البيض', 'El Bayadh'),
	('33', 'Illizi', 'إليزي', 'Illizi'),
	('34', 'Bordj Bou Arreridj', 'برج بوعريريج', 'Bordj Bou Arreridj'),
	('35', 'Boumerdes', 'بومرداس', 'Boumerdes'),
	('36', 'El Tarf', 'الطارف', 'El Tarf'),
	('37', 'Tindouf', 'تندوف', 'Tindouf'),
	('38', 'Tissemsilt', 'تيسمسيلت', 'Tissemsilt'),
	('39', 'El Oued', 'الوادي', 'El Oued'),
	('40', 'Khenechla', 'خنشلة', 'Khenchela'),
	('41', 'Souk Ahras', 'سوق أهراس', 'Souk Ahras'),
	('42', 'Tipaza', 'تيبازة', 'Tipaza'),
	('43', 'Mila', 'ميلة', 'Mila'),
	('44', 'Ain Defla', 'عين الدفلى', 'Ain Defla'),
	('45', 'Naama', 'النعامة', 'Naama'),
	('46', 'Ain Temouchent', 'عين تموشنت', 'Ain Temouchent'),
	('47', 'Ghardaia', 'غرداية', 'Ghardaia'),
	('48', 'Relizane', 'غليزان', 'Relizane'),
	('49', 'Timimoun', 'تيميمون', 'Timimoun'),
	('50', 'Bordj Badj Mokhtar', 'برج باجي مختار', 'Bordj Badji Mokhtar'),
	('51', 'Ouled Djellal', 'أولاد جلال', 'Ouled Djellal'),
	('52', 'Beni Abbes', 'بني عباس', 'Beni Abbes'),
	('53', 'In Salah', 'عين صالح', 'In Salah'),
	('54', 'In Guezzam', 'عين قزام', 'In Guezzam'),
	('55', 'Tougourt', 'تقرت', 'Touggourt'),
	('56', 'Djanet', 'جانت', 'Djanet'),
	('57', 'El Maghair', 'المغير', 'El Meghaier'),
	('58', 'El Meniaa', 'المنيعة', 'El Meniaa');