// Export all entity-specific hooks
export * from "./fiscal";
export * from "./ministries";
export * from "./budget_titles";
export * from "./portfolios";
export * from "./programs";
export * from "./actions";
export * from "./wilayas";
export * from "./operations";
export * from "./engagements";
export * from "./payments";
export * from "./users";
export * from "./enterprises";
export * from "./notifications";
export * from "./comments";
export * from "./documents";
export * from "./previsionsCP";
export * from "./requests";
export * from "./audit_logs";
