// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reczamwtqidertjljcmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlY3phbXd0cWlkZXJ0amxqY212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Nzg1ODcsImV4cCI6MjA1ODI1NDU4N30.kp-KKW7zp1-PiJleL9DCVMXjhsPOz2vRttE1G5edgLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);